apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-ai-ussd-kernel-staging

resources:
  - ../../base
  - ../../vault-csi/secret-provider-class.yaml

commonLabels:
  environment: staging

images:
  - name: openai-ussd-kernel/session-reconstructor
    newTag: latest
  - name: openai-ussd-kernel/payment-engine
    newTag: latest
  - name: openai-ussd-kernel/go-orchestrator
    newTag: latest
  - name: openai-ussd-kernel/python-gateway
    newTag: latest

patches:
  - target:
      kind: Deployment
      name: session-reconstructor
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: payment-engine
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: go-orchestrator
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: python-gateway
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
