# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from openai_ussd_kernel.protos.v1.common import common_pb2 as v1_dot_common_dot_common__pb2
from openai_ussd_kernel.protos.v1.tenant import tenant_pb2 as v1_dot_tenant_dot_tenant__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in v1/tenant/tenant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TenantServiceStub(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - TENANT SERVICE (v1)
    =============================================================================
    Bounded Context: Tenant Management
    Responsibility: Multi-tenancy lifecycle, configuration, provider credentials,
    rate limit policies, entitlement limits, and validation rules.
    Language: Go.
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTenant = channel.unary_unary(
                '/ussd.v1.tenant.TenantService/GetTenant',
                request_serializer=v1_dot_tenant_dot_tenant__pb2.GetTenantRequest.SerializeToString,
                response_deserializer=v1_dot_tenant_dot_tenant__pb2.Tenant.FromString,
                _registered_method=True)
        self.ListTenants = channel.unary_unary(
                '/ussd.v1.tenant.TenantService/ListTenants',
                request_serializer=v1_dot_tenant_dot_tenant__pb2.ListTenantsRequest.SerializeToString,
                response_deserializer=v1_dot_tenant_dot_tenant__pb2.ListTenantsResponse.FromString,
                _registered_method=True)
        self.CreateTenant = channel.unary_unary(
                '/ussd.v1.tenant.TenantService/CreateTenant',
                request_serializer=v1_dot_tenant_dot_tenant__pb2.CreateTenantRequest.SerializeToString,
                response_deserializer=v1_dot_tenant_dot_tenant__pb2.Tenant.FromString,
                _registered_method=True)
        self.UpdateTenant = channel.unary_unary(
                '/ussd.v1.tenant.TenantService/UpdateTenant',
                request_serializer=v1_dot_tenant_dot_tenant__pb2.UpdateTenantRequest.SerializeToString,
                response_deserializer=v1_dot_tenant_dot_tenant__pb2.Tenant.FromString,
                _registered_method=True)
        self.DeleteTenant = channel.unary_unary(
                '/ussd.v1.tenant.TenantService/DeleteTenant',
                request_serializer=v1_dot_tenant_dot_tenant__pb2.DeleteTenantRequest.SerializeToString,
                response_deserializer=v1_dot_tenant_dot_tenant__pb2.DeleteTenantResponse.FromString,
                _registered_method=True)
        self.GetTenantConfig = channel.unary_unary(
                '/ussd.v1.tenant.TenantService/GetTenantConfig',
                request_serializer=v1_dot_tenant_dot_tenant__pb2.GetTenantConfigRequest.SerializeToString,
                response_deserializer=v1_dot_tenant_dot_tenant__pb2.TenantConfig.FromString,
                _registered_method=True)
        self.UpdateTenantConfig = channel.unary_unary(
                '/ussd.v1.tenant.TenantService/UpdateTenantConfig',
                request_serializer=v1_dot_tenant_dot_tenant__pb2.UpdateTenantConfigRequest.SerializeToString,
                response_deserializer=v1_dot_tenant_dot_tenant__pb2.TenantConfig.FromString,
                _registered_method=True)
        self.GetProviderCredentials = channel.unary_unary(
                '/ussd.v1.tenant.TenantService/GetProviderCredentials',
                request_serializer=v1_dot_tenant_dot_tenant__pb2.GetProviderCredentialsRequest.SerializeToString,
                response_deserializer=v1_dot_tenant_dot_tenant__pb2.ProviderCredential.FromString,
                _registered_method=True)
        self.SetProviderCredentials = channel.unary_unary(
                '/ussd.v1.tenant.TenantService/SetProviderCredentials',
                request_serializer=v1_dot_tenant_dot_tenant__pb2.SetProviderCredentialsRequest.SerializeToString,
                response_deserializer=v1_dot_tenant_dot_tenant__pb2.ProviderCredential.FromString,
                _registered_method=True)
        self.GetRateLimitPolicy = channel.unary_unary(
                '/ussd.v1.tenant.TenantService/GetRateLimitPolicy',
                request_serializer=v1_dot_tenant_dot_tenant__pb2.GetRateLimitPolicyRequest.SerializeToString,
                response_deserializer=v1_dot_tenant_dot_tenant__pb2.RateLimitPolicy.FromString,
                _registered_method=True)
        self.ListRateLimitPolicies = channel.unary_unary(
                '/ussd.v1.tenant.TenantService/ListRateLimitPolicies',
                request_serializer=v1_dot_tenant_dot_tenant__pb2.ListRateLimitPoliciesRequest.SerializeToString,
                response_deserializer=v1_dot_tenant_dot_tenant__pb2.ListRateLimitPoliciesResponse.FromString,
                _registered_method=True)
        self.GetEntitlementLimits = channel.unary_unary(
                '/ussd.v1.tenant.TenantService/GetEntitlementLimits',
                request_serializer=v1_dot_tenant_dot_tenant__pb2.GetEntitlementLimitsRequest.SerializeToString,
                response_deserializer=v1_dot_tenant_dot_tenant__pb2.EntitlementLimits.FromString,
                _registered_method=True)
        self.UpdateEntitlementLimits = channel.unary_unary(
                '/ussd.v1.tenant.TenantService/UpdateEntitlementLimits',
                request_serializer=v1_dot_tenant_dot_tenant__pb2.UpdateEntitlementLimitsRequest.SerializeToString,
                response_deserializer=v1_dot_tenant_dot_tenant__pb2.EntitlementLimits.FromString,
                _registered_method=True)
        self.GetValidationRules = channel.unary_unary(
                '/ussd.v1.tenant.TenantService/GetValidationRules',
                request_serializer=v1_dot_tenant_dot_tenant__pb2.GetValidationRulesRequest.SerializeToString,
                response_deserializer=v1_dot_tenant_dot_tenant__pb2.ValidationRulesResponse.FromString,
                _registered_method=True)
        self.UpdateValidationRules = channel.unary_unary(
                '/ussd.v1.tenant.TenantService/UpdateValidationRules',
                request_serializer=v1_dot_tenant_dot_tenant__pb2.UpdateValidationRulesRequest.SerializeToString,
                response_deserializer=v1_dot_tenant_dot_tenant__pb2.ValidationRulesResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ussd.v1.tenant.TenantService/Health',
                request_serializer=v1_dot_common_dot_common__pb2.HealthRequest.SerializeToString,
                response_deserializer=v1_dot_common_dot_common__pb2.HealthResponse.FromString,
                _registered_method=True)


class TenantServiceServicer(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - TENANT SERVICE (v1)
    =============================================================================
    Bounded Context: Tenant Management
    Responsibility: Multi-tenancy lifecycle, configuration, provider credentials,
    rate limit policies, entitlement limits, and validation rules.
    Language: Go.
    =============================================================================

    """

    def GetTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTenants(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTenant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTenantConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTenantConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProviderCredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetProviderCredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRateLimitPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRateLimitPolicies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntitlementLimits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEntitlementLimits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetValidationRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateValidationRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TenantServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTenant,
                    request_deserializer=v1_dot_tenant_dot_tenant__pb2.GetTenantRequest.FromString,
                    response_serializer=v1_dot_tenant_dot_tenant__pb2.Tenant.SerializeToString,
            ),
            'ListTenants': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTenants,
                    request_deserializer=v1_dot_tenant_dot_tenant__pb2.ListTenantsRequest.FromString,
                    response_serializer=v1_dot_tenant_dot_tenant__pb2.ListTenantsResponse.SerializeToString,
            ),
            'CreateTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTenant,
                    request_deserializer=v1_dot_tenant_dot_tenant__pb2.CreateTenantRequest.FromString,
                    response_serializer=v1_dot_tenant_dot_tenant__pb2.Tenant.SerializeToString,
            ),
            'UpdateTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTenant,
                    request_deserializer=v1_dot_tenant_dot_tenant__pb2.UpdateTenantRequest.FromString,
                    response_serializer=v1_dot_tenant_dot_tenant__pb2.Tenant.SerializeToString,
            ),
            'DeleteTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTenant,
                    request_deserializer=v1_dot_tenant_dot_tenant__pb2.DeleteTenantRequest.FromString,
                    response_serializer=v1_dot_tenant_dot_tenant__pb2.DeleteTenantResponse.SerializeToString,
            ),
            'GetTenantConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTenantConfig,
                    request_deserializer=v1_dot_tenant_dot_tenant__pb2.GetTenantConfigRequest.FromString,
                    response_serializer=v1_dot_tenant_dot_tenant__pb2.TenantConfig.SerializeToString,
            ),
            'UpdateTenantConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTenantConfig,
                    request_deserializer=v1_dot_tenant_dot_tenant__pb2.UpdateTenantConfigRequest.FromString,
                    response_serializer=v1_dot_tenant_dot_tenant__pb2.TenantConfig.SerializeToString,
            ),
            'GetProviderCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProviderCredentials,
                    request_deserializer=v1_dot_tenant_dot_tenant__pb2.GetProviderCredentialsRequest.FromString,
                    response_serializer=v1_dot_tenant_dot_tenant__pb2.ProviderCredential.SerializeToString,
            ),
            'SetProviderCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProviderCredentials,
                    request_deserializer=v1_dot_tenant_dot_tenant__pb2.SetProviderCredentialsRequest.FromString,
                    response_serializer=v1_dot_tenant_dot_tenant__pb2.ProviderCredential.SerializeToString,
            ),
            'GetRateLimitPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRateLimitPolicy,
                    request_deserializer=v1_dot_tenant_dot_tenant__pb2.GetRateLimitPolicyRequest.FromString,
                    response_serializer=v1_dot_tenant_dot_tenant__pb2.RateLimitPolicy.SerializeToString,
            ),
            'ListRateLimitPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRateLimitPolicies,
                    request_deserializer=v1_dot_tenant_dot_tenant__pb2.ListRateLimitPoliciesRequest.FromString,
                    response_serializer=v1_dot_tenant_dot_tenant__pb2.ListRateLimitPoliciesResponse.SerializeToString,
            ),
            'GetEntitlementLimits': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntitlementLimits,
                    request_deserializer=v1_dot_tenant_dot_tenant__pb2.GetEntitlementLimitsRequest.FromString,
                    response_serializer=v1_dot_tenant_dot_tenant__pb2.EntitlementLimits.SerializeToString,
            ),
            'UpdateEntitlementLimits': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEntitlementLimits,
                    request_deserializer=v1_dot_tenant_dot_tenant__pb2.UpdateEntitlementLimitsRequest.FromString,
                    response_serializer=v1_dot_tenant_dot_tenant__pb2.EntitlementLimits.SerializeToString,
            ),
            'GetValidationRules': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValidationRules,
                    request_deserializer=v1_dot_tenant_dot_tenant__pb2.GetValidationRulesRequest.FromString,
                    response_serializer=v1_dot_tenant_dot_tenant__pb2.ValidationRulesResponse.SerializeToString,
            ),
            'UpdateValidationRules': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateValidationRules,
                    request_deserializer=v1_dot_tenant_dot_tenant__pb2.UpdateValidationRulesRequest.FromString,
                    response_serializer=v1_dot_tenant_dot_tenant__pb2.ValidationRulesResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=v1_dot_common_dot_common__pb2.HealthRequest.FromString,
                    response_serializer=v1_dot_common_dot_common__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ussd.v1.tenant.TenantService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ussd.v1.tenant.TenantService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TenantService(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - TENANT SERVICE (v1)
    =============================================================================
    Bounded Context: Tenant Management
    Responsibility: Multi-tenancy lifecycle, configuration, provider credentials,
    rate limit policies, entitlement limits, and validation rules.
    Language: Go.
    =============================================================================

    """

    @staticmethod
    def GetTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.tenant.TenantService/GetTenant',
            v1_dot_tenant_dot_tenant__pb2.GetTenantRequest.SerializeToString,
            v1_dot_tenant_dot_tenant__pb2.Tenant.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTenants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.tenant.TenantService/ListTenants',
            v1_dot_tenant_dot_tenant__pb2.ListTenantsRequest.SerializeToString,
            v1_dot_tenant_dot_tenant__pb2.ListTenantsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.tenant.TenantService/CreateTenant',
            v1_dot_tenant_dot_tenant__pb2.CreateTenantRequest.SerializeToString,
            v1_dot_tenant_dot_tenant__pb2.Tenant.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.tenant.TenantService/UpdateTenant',
            v1_dot_tenant_dot_tenant__pb2.UpdateTenantRequest.SerializeToString,
            v1_dot_tenant_dot_tenant__pb2.Tenant.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.tenant.TenantService/DeleteTenant',
            v1_dot_tenant_dot_tenant__pb2.DeleteTenantRequest.SerializeToString,
            v1_dot_tenant_dot_tenant__pb2.DeleteTenantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTenantConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.tenant.TenantService/GetTenantConfig',
            v1_dot_tenant_dot_tenant__pb2.GetTenantConfigRequest.SerializeToString,
            v1_dot_tenant_dot_tenant__pb2.TenantConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTenantConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.tenant.TenantService/UpdateTenantConfig',
            v1_dot_tenant_dot_tenant__pb2.UpdateTenantConfigRequest.SerializeToString,
            v1_dot_tenant_dot_tenant__pb2.TenantConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProviderCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.tenant.TenantService/GetProviderCredentials',
            v1_dot_tenant_dot_tenant__pb2.GetProviderCredentialsRequest.SerializeToString,
            v1_dot_tenant_dot_tenant__pb2.ProviderCredential.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetProviderCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.tenant.TenantService/SetProviderCredentials',
            v1_dot_tenant_dot_tenant__pb2.SetProviderCredentialsRequest.SerializeToString,
            v1_dot_tenant_dot_tenant__pb2.ProviderCredential.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRateLimitPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.tenant.TenantService/GetRateLimitPolicy',
            v1_dot_tenant_dot_tenant__pb2.GetRateLimitPolicyRequest.SerializeToString,
            v1_dot_tenant_dot_tenant__pb2.RateLimitPolicy.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRateLimitPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.tenant.TenantService/ListRateLimitPolicies',
            v1_dot_tenant_dot_tenant__pb2.ListRateLimitPoliciesRequest.SerializeToString,
            v1_dot_tenant_dot_tenant__pb2.ListRateLimitPoliciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntitlementLimits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.tenant.TenantService/GetEntitlementLimits',
            v1_dot_tenant_dot_tenant__pb2.GetEntitlementLimitsRequest.SerializeToString,
            v1_dot_tenant_dot_tenant__pb2.EntitlementLimits.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEntitlementLimits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.tenant.TenantService/UpdateEntitlementLimits',
            v1_dot_tenant_dot_tenant__pb2.UpdateEntitlementLimitsRequest.SerializeToString,
            v1_dot_tenant_dot_tenant__pb2.EntitlementLimits.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetValidationRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.tenant.TenantService/GetValidationRules',
            v1_dot_tenant_dot_tenant__pb2.GetValidationRulesRequest.SerializeToString,
            v1_dot_tenant_dot_tenant__pb2.ValidationRulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateValidationRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.tenant.TenantService/UpdateValidationRules',
            v1_dot_tenant_dot_tenant__pb2.UpdateValidationRulesRequest.SerializeToString,
            v1_dot_tenant_dot_tenant__pb2.ValidationRulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.tenant.TenantService/Health',
            v1_dot_common_dot_common__pb2.HealthRequest.SerializeToString,
            v1_dot_common_dot_common__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
