# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from openai_ussd_kernel.protos.v1.ai import ai_pb2 as v1_dot_ai_dot_ai__pb2
from openai_ussd_kernel.protos.v1.common import common_pb2 as v1_dot_common_dot_common__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in v1/ai/ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIBrainStub(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - AI BRAIN SERVICE (v1)
    =============================================================================
    Bounded Context: AI & Personalization
    Responsibility: Small Language Model inference, translation, intent detection,
    entity extraction, session summarization, and predictive personalization.
    Language: Python (PyTorch / Hugging Face).
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Translate = channel.unary_unary(
                '/ussd.v1.ai.AIBrain/Translate',
                request_serializer=v1_dot_ai_dot_ai__pb2.TranslateRequest.SerializeToString,
                response_deserializer=v1_dot_ai_dot_ai__pb2.TranslateResponse.FromString,
                _registered_method=True)
        self.Personalize = channel.unary_unary(
                '/ussd.v1.ai.AIBrain/Personalize',
                request_serializer=v1_dot_ai_dot_ai__pb2.PersonalizeRequest.SerializeToString,
                response_deserializer=v1_dot_ai_dot_ai__pb2.PersonalizeResponse.FromString,
                _registered_method=True)
        self.Predict = channel.unary_unary(
                '/ussd.v1.ai.AIBrain/Predict',
                request_serializer=v1_dot_ai_dot_ai__pb2.PredictRequest.SerializeToString,
                response_deserializer=v1_dot_ai_dot_ai__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.DetectIntent = channel.unary_unary(
                '/ussd.v1.ai.AIBrain/DetectIntent',
                request_serializer=v1_dot_ai_dot_ai__pb2.DetectIntentRequest.SerializeToString,
                response_deserializer=v1_dot_ai_dot_ai__pb2.DetectIntentResponse.FromString,
                _registered_method=True)
        self.ExtractEntities = channel.unary_unary(
                '/ussd.v1.ai.AIBrain/ExtractEntities',
                request_serializer=v1_dot_ai_dot_ai__pb2.ExtractEntitiesRequest.SerializeToString,
                response_deserializer=v1_dot_ai_dot_ai__pb2.ExtractEntitiesResponse.FromString,
                _registered_method=True)
        self.SummarizeSession = channel.unary_unary(
                '/ussd.v1.ai.AIBrain/SummarizeSession',
                request_serializer=v1_dot_ai_dot_ai__pb2.SummarizeSessionRequest.SerializeToString,
                response_deserializer=v1_dot_ai_dot_ai__pb2.SummarizeSessionResponse.FromString,
                _registered_method=True)
        self.GetEmbedding = channel.unary_unary(
                '/ussd.v1.ai.AIBrain/GetEmbedding',
                request_serializer=v1_dot_ai_dot_ai__pb2.GetEmbeddingRequest.SerializeToString,
                response_deserializer=v1_dot_ai_dot_ai__pb2.GetEmbeddingResponse.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/ussd.v1.ai.AIBrain/GetModelInfo',
                request_serializer=v1_dot_ai_dot_ai__pb2.GetModelInfoRequest.SerializeToString,
                response_deserializer=v1_dot_ai_dot_ai__pb2.ModelInfo.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/ussd.v1.ai.AIBrain/ListModels',
                request_serializer=v1_dot_ai_dot_ai__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=v1_dot_ai_dot_ai__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ussd.v1.ai.AIBrain/Health',
                request_serializer=v1_dot_common_dot_common__pb2.HealthRequest.SerializeToString,
                response_deserializer=v1_dot_common_dot_common__pb2.HealthResponse.FromString,
                _registered_method=True)


class AIBrainServicer(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - AI BRAIN SERVICE (v1)
    =============================================================================
    Bounded Context: AI & Personalization
    Responsibility: Small Language Model inference, translation, intent detection,
    entity extraction, session summarization, and predictive personalization.
    Language: Python (PyTorch / Hugging Face).
    =============================================================================

    """

    def Translate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Personalize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectIntent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractEntities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SummarizeSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIBrainServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Translate': grpc.unary_unary_rpc_method_handler(
                    servicer.Translate,
                    request_deserializer=v1_dot_ai_dot_ai__pb2.TranslateRequest.FromString,
                    response_serializer=v1_dot_ai_dot_ai__pb2.TranslateResponse.SerializeToString,
            ),
            'Personalize': grpc.unary_unary_rpc_method_handler(
                    servicer.Personalize,
                    request_deserializer=v1_dot_ai_dot_ai__pb2.PersonalizeRequest.FromString,
                    response_serializer=v1_dot_ai_dot_ai__pb2.PersonalizeResponse.SerializeToString,
            ),
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=v1_dot_ai_dot_ai__pb2.PredictRequest.FromString,
                    response_serializer=v1_dot_ai_dot_ai__pb2.PredictResponse.SerializeToString,
            ),
            'DetectIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectIntent,
                    request_deserializer=v1_dot_ai_dot_ai__pb2.DetectIntentRequest.FromString,
                    response_serializer=v1_dot_ai_dot_ai__pb2.DetectIntentResponse.SerializeToString,
            ),
            'ExtractEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractEntities,
                    request_deserializer=v1_dot_ai_dot_ai__pb2.ExtractEntitiesRequest.FromString,
                    response_serializer=v1_dot_ai_dot_ai__pb2.ExtractEntitiesResponse.SerializeToString,
            ),
            'SummarizeSession': grpc.unary_unary_rpc_method_handler(
                    servicer.SummarizeSession,
                    request_deserializer=v1_dot_ai_dot_ai__pb2.SummarizeSessionRequest.FromString,
                    response_serializer=v1_dot_ai_dot_ai__pb2.SummarizeSessionResponse.SerializeToString,
            ),
            'GetEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbedding,
                    request_deserializer=v1_dot_ai_dot_ai__pb2.GetEmbeddingRequest.FromString,
                    response_serializer=v1_dot_ai_dot_ai__pb2.GetEmbeddingResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=v1_dot_ai_dot_ai__pb2.GetModelInfoRequest.FromString,
                    response_serializer=v1_dot_ai_dot_ai__pb2.ModelInfo.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=v1_dot_ai_dot_ai__pb2.ListModelsRequest.FromString,
                    response_serializer=v1_dot_ai_dot_ai__pb2.ListModelsResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=v1_dot_common_dot_common__pb2.HealthRequest.FromString,
                    response_serializer=v1_dot_common_dot_common__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ussd.v1.ai.AIBrain', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ussd.v1.ai.AIBrain', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIBrain(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - AI BRAIN SERVICE (v1)
    =============================================================================
    Bounded Context: AI & Personalization
    Responsibility: Small Language Model inference, translation, intent detection,
    entity extraction, session summarization, and predictive personalization.
    Language: Python (PyTorch / Hugging Face).
    =============================================================================

    """

    @staticmethod
    def Translate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.ai.AIBrain/Translate',
            v1_dot_ai_dot_ai__pb2.TranslateRequest.SerializeToString,
            v1_dot_ai_dot_ai__pb2.TranslateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Personalize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.ai.AIBrain/Personalize',
            v1_dot_ai_dot_ai__pb2.PersonalizeRequest.SerializeToString,
            v1_dot_ai_dot_ai__pb2.PersonalizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.ai.AIBrain/Predict',
            v1_dot_ai_dot_ai__pb2.PredictRequest.SerializeToString,
            v1_dot_ai_dot_ai__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.ai.AIBrain/DetectIntent',
            v1_dot_ai_dot_ai__pb2.DetectIntentRequest.SerializeToString,
            v1_dot_ai_dot_ai__pb2.DetectIntentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.ai.AIBrain/ExtractEntities',
            v1_dot_ai_dot_ai__pb2.ExtractEntitiesRequest.SerializeToString,
            v1_dot_ai_dot_ai__pb2.ExtractEntitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SummarizeSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.ai.AIBrain/SummarizeSession',
            v1_dot_ai_dot_ai__pb2.SummarizeSessionRequest.SerializeToString,
            v1_dot_ai_dot_ai__pb2.SummarizeSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.ai.AIBrain/GetEmbedding',
            v1_dot_ai_dot_ai__pb2.GetEmbeddingRequest.SerializeToString,
            v1_dot_ai_dot_ai__pb2.GetEmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.ai.AIBrain/GetModelInfo',
            v1_dot_ai_dot_ai__pb2.GetModelInfoRequest.SerializeToString,
            v1_dot_ai_dot_ai__pb2.ModelInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.ai.AIBrain/ListModels',
            v1_dot_ai_dot_ai__pb2.ListModelsRequest.SerializeToString,
            v1_dot_ai_dot_ai__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.ai.AIBrain/Health',
            v1_dot_common_dot_common__pb2.HealthRequest.SerializeToString,
            v1_dot_common_dot_common__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
