# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from openai_ussd_kernel.protos.v1.common import common_pb2 as v1_dot_common_dot_common__pb2
from openai_ussd_kernel.protos.v1.payment import payment_pb2 as v1_dot_payment_dot_payment__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in v1/payment/payment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentEngineStub(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - PAYMENT ENGINE SERVICE (v1)
    =============================================================================
    Bounded Context: Payment Processing
    Responsibility: Mobile money integration (EcoCash, OneMoney, TeleCash),
    disbursements, refunds, reversals, settlements, disputes, and provider
    callback handling.
    Language: Rust (high-performance financial engine).
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitiatePayment = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/InitiatePayment',
                request_serializer=v1_dot_payment_dot_payment__pb2.InitiatePaymentRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.InitiatePaymentResponse.FromString,
                _registered_method=True)
        self.PreviewPayment = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/PreviewPayment',
                request_serializer=v1_dot_payment_dot_payment__pb2.PreviewPaymentRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.PreviewPaymentResponse.FromString,
                _registered_method=True)
        self.BulkInitiatePayment = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/BulkInitiatePayment',
                request_serializer=v1_dot_payment_dot_payment__pb2.BulkInitiatePaymentRequest.SerializeToString,
                response_deserializer=v1_dot_common_dot_common__pb2.BatchOperationResult.FromString,
                _registered_method=True)
        self.InitiateDisbursement = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/InitiateDisbursement',
                request_serializer=v1_dot_payment_dot_payment__pb2.InitiateDisbursementRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.InitiateDisbursementResponse.FromString,
                _registered_method=True)
        self.BulkInitiateDisbursement = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/BulkInitiateDisbursement',
                request_serializer=v1_dot_payment_dot_payment__pb2.BulkInitiateDisbursementRequest.SerializeToString,
                response_deserializer=v1_dot_common_dot_common__pb2.BatchOperationResult.FromString,
                _registered_method=True)
        self.GetPaymentStatus = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/GetPaymentStatus',
                request_serializer=v1_dot_payment_dot_payment__pb2.GetPaymentStatusRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.GetPaymentStatusResponse.FromString,
                _registered_method=True)
        self.GetPaymentDetails = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/GetPaymentDetails',
                request_serializer=v1_dot_payment_dot_payment__pb2.GetPaymentDetailsRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.GetPaymentDetailsResponse.FromString,
                _registered_method=True)
        self.RefundPayment = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/RefundPayment',
                request_serializer=v1_dot_payment_dot_payment__pb2.RefundPaymentRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.RefundPaymentResponse.FromString,
                _registered_method=True)
        self.ReversePayment = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/ReversePayment',
                request_serializer=v1_dot_payment_dot_payment__pb2.ReversePaymentRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.ReversePaymentResponse.FromString,
                _registered_method=True)
        self.ListPayments = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/ListPayments',
                request_serializer=v1_dot_payment_dot_payment__pb2.ListPaymentsRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.ListPaymentsResponse.FromString,
                _registered_method=True)
        self.GetPaymentAnalytics = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/GetPaymentAnalytics',
                request_serializer=v1_dot_payment_dot_payment__pb2.GetPaymentAnalyticsRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.GetPaymentAnalyticsResponse.FromString,
                _registered_method=True)
        self.ValidatePhoneNumber = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/ValidatePhoneNumber',
                request_serializer=v1_dot_payment_dot_payment__pb2.ValidatePhoneNumberRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.ValidatePhoneNumberResponse.FromString,
                _registered_method=True)
        self.GetProviderBalance = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/GetProviderBalance',
                request_serializer=v1_dot_payment_dot_payment__pb2.GetProviderBalanceRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.GetProviderBalanceResponse.FromString,
                _registered_method=True)
        self.GetProviderCapabilities = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/GetProviderCapabilities',
                request_serializer=v1_dot_payment_dot_payment__pb2.GetProviderCapabilitiesRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.GetProviderCapabilitiesResponse.FromString,
                _registered_method=True)
        self.ProcessCallback = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/ProcessCallback',
                request_serializer=v1_dot_payment_dot_payment__pb2.ProcessCallbackRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.ProcessCallbackResponse.FromString,
                _registered_method=True)
        self.ReportDispute = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/ReportDispute',
                request_serializer=v1_dot_payment_dot_payment__pb2.ReportDisputeRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.ReportDisputeResponse.FromString,
                _registered_method=True)
        self.UpdateDispute = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/UpdateDispute',
                request_serializer=v1_dot_payment_dot_payment__pb2.UpdateDisputeRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.Dispute.FromString,
                _registered_method=True)
        self.UploadDisputeEvidence = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/UploadDisputeEvidence',
                request_serializer=v1_dot_payment_dot_payment__pb2.UploadDisputeEvidenceRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.UploadDisputeEvidenceResponse.FromString,
                _registered_method=True)
        self.GetDisputeStatus = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/GetDisputeStatus',
                request_serializer=v1_dot_payment_dot_payment__pb2.GetDisputeStatusRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.Dispute.FromString,
                _registered_method=True)
        self.ListDisputes = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/ListDisputes',
                request_serializer=v1_dot_payment_dot_payment__pb2.ListDisputesRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.ListDisputesResponse.FromString,
                _registered_method=True)
        self.GenerateSettlementFile = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/GenerateSettlementFile',
                request_serializer=v1_dot_payment_dot_payment__pb2.GenerateSettlementFileRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.GenerateSettlementFileResponse.FromString,
                _registered_method=True)
        self.GetSettlementFile = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/GetSettlementFile',
                request_serializer=v1_dot_payment_dot_payment__pb2.GetSettlementFileRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.SettlementFile.FromString,
                _registered_method=True)
        self.ListSettlementFiles = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/ListSettlementFiles',
                request_serializer=v1_dot_payment_dot_payment__pb2.ListSettlementFilesRequest.SerializeToString,
                response_deserializer=v1_dot_payment_dot_payment__pb2.ListSettlementFilesResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ussd.v1.payment.PaymentEngine/Health',
                request_serializer=v1_dot_common_dot_common__pb2.HealthRequest.SerializeToString,
                response_deserializer=v1_dot_common_dot_common__pb2.HealthResponse.FromString,
                _registered_method=True)


class PaymentEngineServicer(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - PAYMENT ENGINE SERVICE (v1)
    =============================================================================
    Bounded Context: Payment Processing
    Responsibility: Mobile money integration (EcoCash, OneMoney, TeleCash),
    disbursements, refunds, reversals, settlements, disputes, and provider
    callback handling.
    Language: Rust (high-performance financial engine).
    =============================================================================

    """

    def InitiatePayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreviewPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkInitiatePayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitiateDisbursement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkInitiateDisbursement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPaymentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPaymentDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefundPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReversePayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPayments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPaymentAnalytics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidatePhoneNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProviderBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProviderCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessCallback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportDispute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDispute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadDisputeEvidence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDisputeStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDisputes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateSettlementFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSettlementFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSettlementFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitiatePayment': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiatePayment,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.InitiatePaymentRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.InitiatePaymentResponse.SerializeToString,
            ),
            'PreviewPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.PreviewPayment,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.PreviewPaymentRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.PreviewPaymentResponse.SerializeToString,
            ),
            'BulkInitiatePayment': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkInitiatePayment,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.BulkInitiatePaymentRequest.FromString,
                    response_serializer=v1_dot_common_dot_common__pb2.BatchOperationResult.SerializeToString,
            ),
            'InitiateDisbursement': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiateDisbursement,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.InitiateDisbursementRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.InitiateDisbursementResponse.SerializeToString,
            ),
            'BulkInitiateDisbursement': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkInitiateDisbursement,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.BulkInitiateDisbursementRequest.FromString,
                    response_serializer=v1_dot_common_dot_common__pb2.BatchOperationResult.SerializeToString,
            ),
            'GetPaymentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPaymentStatus,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.GetPaymentStatusRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.GetPaymentStatusResponse.SerializeToString,
            ),
            'GetPaymentDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPaymentDetails,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.GetPaymentDetailsRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.GetPaymentDetailsResponse.SerializeToString,
            ),
            'RefundPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.RefundPayment,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.RefundPaymentRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.RefundPaymentResponse.SerializeToString,
            ),
            'ReversePayment': grpc.unary_unary_rpc_method_handler(
                    servicer.ReversePayment,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.ReversePaymentRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.ReversePaymentResponse.SerializeToString,
            ),
            'ListPayments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPayments,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.ListPaymentsRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.ListPaymentsResponse.SerializeToString,
            ),
            'GetPaymentAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPaymentAnalytics,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.GetPaymentAnalyticsRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.GetPaymentAnalyticsResponse.SerializeToString,
            ),
            'ValidatePhoneNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidatePhoneNumber,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.ValidatePhoneNumberRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.ValidatePhoneNumberResponse.SerializeToString,
            ),
            'GetProviderBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProviderBalance,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.GetProviderBalanceRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.GetProviderBalanceResponse.SerializeToString,
            ),
            'GetProviderCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProviderCapabilities,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.GetProviderCapabilitiesRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.GetProviderCapabilitiesResponse.SerializeToString,
            ),
            'ProcessCallback': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessCallback,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.ProcessCallbackRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.ProcessCallbackResponse.SerializeToString,
            ),
            'ReportDispute': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportDispute,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.ReportDisputeRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.ReportDisputeResponse.SerializeToString,
            ),
            'UpdateDispute': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDispute,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.UpdateDisputeRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.Dispute.SerializeToString,
            ),
            'UploadDisputeEvidence': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadDisputeEvidence,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.UploadDisputeEvidenceRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.UploadDisputeEvidenceResponse.SerializeToString,
            ),
            'GetDisputeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDisputeStatus,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.GetDisputeStatusRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.Dispute.SerializeToString,
            ),
            'ListDisputes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDisputes,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.ListDisputesRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.ListDisputesResponse.SerializeToString,
            ),
            'GenerateSettlementFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSettlementFile,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.GenerateSettlementFileRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.GenerateSettlementFileResponse.SerializeToString,
            ),
            'GetSettlementFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSettlementFile,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.GetSettlementFileRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.SettlementFile.SerializeToString,
            ),
            'ListSettlementFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSettlementFiles,
                    request_deserializer=v1_dot_payment_dot_payment__pb2.ListSettlementFilesRequest.FromString,
                    response_serializer=v1_dot_payment_dot_payment__pb2.ListSettlementFilesResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=v1_dot_common_dot_common__pb2.HealthRequest.FromString,
                    response_serializer=v1_dot_common_dot_common__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ussd.v1.payment.PaymentEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ussd.v1.payment.PaymentEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentEngine(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - PAYMENT ENGINE SERVICE (v1)
    =============================================================================
    Bounded Context: Payment Processing
    Responsibility: Mobile money integration (EcoCash, OneMoney, TeleCash),
    disbursements, refunds, reversals, settlements, disputes, and provider
    callback handling.
    Language: Rust (high-performance financial engine).
    =============================================================================

    """

    @staticmethod
    def InitiatePayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/InitiatePayment',
            v1_dot_payment_dot_payment__pb2.InitiatePaymentRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.InitiatePaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreviewPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/PreviewPayment',
            v1_dot_payment_dot_payment__pb2.PreviewPaymentRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.PreviewPaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkInitiatePayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/BulkInitiatePayment',
            v1_dot_payment_dot_payment__pb2.BulkInitiatePaymentRequest.SerializeToString,
            v1_dot_common_dot_common__pb2.BatchOperationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitiateDisbursement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/InitiateDisbursement',
            v1_dot_payment_dot_payment__pb2.InitiateDisbursementRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.InitiateDisbursementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkInitiateDisbursement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/BulkInitiateDisbursement',
            v1_dot_payment_dot_payment__pb2.BulkInitiateDisbursementRequest.SerializeToString,
            v1_dot_common_dot_common__pb2.BatchOperationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPaymentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/GetPaymentStatus',
            v1_dot_payment_dot_payment__pb2.GetPaymentStatusRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.GetPaymentStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPaymentDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/GetPaymentDetails',
            v1_dot_payment_dot_payment__pb2.GetPaymentDetailsRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.GetPaymentDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefundPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/RefundPayment',
            v1_dot_payment_dot_payment__pb2.RefundPaymentRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.RefundPaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReversePayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/ReversePayment',
            v1_dot_payment_dot_payment__pb2.ReversePaymentRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.ReversePaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPayments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/ListPayments',
            v1_dot_payment_dot_payment__pb2.ListPaymentsRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.ListPaymentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPaymentAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/GetPaymentAnalytics',
            v1_dot_payment_dot_payment__pb2.GetPaymentAnalyticsRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.GetPaymentAnalyticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidatePhoneNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/ValidatePhoneNumber',
            v1_dot_payment_dot_payment__pb2.ValidatePhoneNumberRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.ValidatePhoneNumberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProviderBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/GetProviderBalance',
            v1_dot_payment_dot_payment__pb2.GetProviderBalanceRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.GetProviderBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProviderCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/GetProviderCapabilities',
            v1_dot_payment_dot_payment__pb2.GetProviderCapabilitiesRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.GetProviderCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessCallback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/ProcessCallback',
            v1_dot_payment_dot_payment__pb2.ProcessCallbackRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.ProcessCallbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportDispute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/ReportDispute',
            v1_dot_payment_dot_payment__pb2.ReportDisputeRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.ReportDisputeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDispute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/UpdateDispute',
            v1_dot_payment_dot_payment__pb2.UpdateDisputeRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.Dispute.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadDisputeEvidence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/UploadDisputeEvidence',
            v1_dot_payment_dot_payment__pb2.UploadDisputeEvidenceRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.UploadDisputeEvidenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDisputeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/GetDisputeStatus',
            v1_dot_payment_dot_payment__pb2.GetDisputeStatusRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.Dispute.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDisputes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/ListDisputes',
            v1_dot_payment_dot_payment__pb2.ListDisputesRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.ListDisputesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateSettlementFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/GenerateSettlementFile',
            v1_dot_payment_dot_payment__pb2.GenerateSettlementFileRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.GenerateSettlementFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSettlementFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/GetSettlementFile',
            v1_dot_payment_dot_payment__pb2.GetSettlementFileRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.SettlementFile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSettlementFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/ListSettlementFiles',
            v1_dot_payment_dot_payment__pb2.ListSettlementFilesRequest.SerializeToString,
            v1_dot_payment_dot_payment__pb2.ListSettlementFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.payment.PaymentEngine/Health',
            v1_dot_common_dot_common__pb2.HealthRequest.SerializeToString,
            v1_dot_common_dot_common__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
