# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from openai_ussd_kernel.protos.v1.audit import audit_pb2 as v1_dot_audit_dot_audit__pb2
from openai_ussd_kernel.protos.v1.common import common_pb2 as v1_dot_common_dot_common__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in v1/audit/audit_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuditServiceStub(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - AUDIT SERVICE (v1)
    =============================================================================
    Bounded Context: Audit & Integrity
    Responsibility: Tamper-evident audit log, Merkle proofs, cryptographic batch
    integrity verification, hash chain validation, and signed audit reports.
    Language: Rust (cryptographic performance).
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMerkleProof = channel.unary_unary(
                '/ussd.v1.audit.AuditService/GetMerkleProof',
                request_serializer=v1_dot_audit_dot_audit__pb2.GetMerkleProofRequest.SerializeToString,
                response_deserializer=v1_dot_audit_dot_audit__pb2.GetMerkleProofResponse.FromString,
                _registered_method=True)
        self.GetLedgerChecksum = channel.unary_unary(
                '/ussd.v1.audit.AuditService/GetLedgerChecksum',
                request_serializer=v1_dot_audit_dot_audit__pb2.GetLedgerChecksumRequest.SerializeToString,
                response_deserializer=v1_dot_audit_dot_audit__pb2.GetLedgerChecksumResponse.FromString,
                _registered_method=True)
        self.VerifyBatchIntegrity = channel.unary_unary(
                '/ussd.v1.audit.AuditService/VerifyBatchIntegrity',
                request_serializer=v1_dot_audit_dot_audit__pb2.VerifyBatchIntegrityRequest.SerializeToString,
                response_deserializer=v1_dot_audit_dot_audit__pb2.VerifyBatchIntegrityResponse.FromString,
                _registered_method=True)
        self.StreamAuditEvents = channel.unary_stream(
                '/ussd.v1.audit.AuditService/StreamAuditEvents',
                request_serializer=v1_dot_audit_dot_audit__pb2.StreamAuditEventsRequest.SerializeToString,
                response_deserializer=v1_dot_common_dot_common__pb2.EventEnvelope.FromString,
                _registered_method=True)
        self.VerifyTransactionChain = channel.unary_unary(
                '/ussd.v1.audit.AuditService/VerifyTransactionChain',
                request_serializer=v1_dot_audit_dot_audit__pb2.VerifyTransactionChainRequest.SerializeToString,
                response_deserializer=v1_dot_audit_dot_audit__pb2.TransactionChainReport.FromString,
                _registered_method=True)
        self.GetAuditTrail = channel.unary_stream(
                '/ussd.v1.audit.AuditService/GetAuditTrail',
                request_serializer=v1_dot_audit_dot_audit__pb2.GetAuditTrailRequest.SerializeToString,
                response_deserializer=v1_dot_audit_dot_audit__pb2.AuditEntry.FromString,
                _registered_method=True)
        self.GetAuditReport = channel.unary_unary(
                '/ussd.v1.audit.AuditService/GetAuditReport',
                request_serializer=v1_dot_audit_dot_audit__pb2.GetAuditReportRequest.SerializeToString,
                response_deserializer=v1_dot_audit_dot_audit__pb2.GetAuditReportResponse.FromString,
                _registered_method=True)
        self.ExportAuditReport = channel.unary_unary(
                '/ussd.v1.audit.AuditService/ExportAuditReport',
                request_serializer=v1_dot_audit_dot_audit__pb2.ExportAuditReportRequest.SerializeToString,
                response_deserializer=v1_dot_audit_dot_audit__pb2.ExportAuditReportResponse.FromString,
                _registered_method=True)
        self.GetSigningKeys = channel.unary_unary(
                '/ussd.v1.audit.AuditService/GetSigningKeys',
                request_serializer=v1_dot_audit_dot_audit__pb2.GetSigningKeysRequest.SerializeToString,
                response_deserializer=v1_dot_audit_dot_audit__pb2.GetSigningKeysResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ussd.v1.audit.AuditService/Health',
                request_serializer=v1_dot_common_dot_common__pb2.HealthRequest.SerializeToString,
                response_deserializer=v1_dot_common_dot_common__pb2.HealthResponse.FromString,
                _registered_method=True)


class AuditServiceServicer(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - AUDIT SERVICE (v1)
    =============================================================================
    Bounded Context: Audit & Integrity
    Responsibility: Tamper-evident audit log, Merkle proofs, cryptographic batch
    integrity verification, hash chain validation, and signed audit reports.
    Language: Rust (cryptographic performance).
    =============================================================================

    """

    def GetMerkleProof(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLedgerChecksum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyBatchIntegrity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAuditEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyTransactionChain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuditTrail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuditReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportAuditReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSigningKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuditServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMerkleProof': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMerkleProof,
                    request_deserializer=v1_dot_audit_dot_audit__pb2.GetMerkleProofRequest.FromString,
                    response_serializer=v1_dot_audit_dot_audit__pb2.GetMerkleProofResponse.SerializeToString,
            ),
            'GetLedgerChecksum': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLedgerChecksum,
                    request_deserializer=v1_dot_audit_dot_audit__pb2.GetLedgerChecksumRequest.FromString,
                    response_serializer=v1_dot_audit_dot_audit__pb2.GetLedgerChecksumResponse.SerializeToString,
            ),
            'VerifyBatchIntegrity': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyBatchIntegrity,
                    request_deserializer=v1_dot_audit_dot_audit__pb2.VerifyBatchIntegrityRequest.FromString,
                    response_serializer=v1_dot_audit_dot_audit__pb2.VerifyBatchIntegrityResponse.SerializeToString,
            ),
            'StreamAuditEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAuditEvents,
                    request_deserializer=v1_dot_audit_dot_audit__pb2.StreamAuditEventsRequest.FromString,
                    response_serializer=v1_dot_common_dot_common__pb2.EventEnvelope.SerializeToString,
            ),
            'VerifyTransactionChain': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyTransactionChain,
                    request_deserializer=v1_dot_audit_dot_audit__pb2.VerifyTransactionChainRequest.FromString,
                    response_serializer=v1_dot_audit_dot_audit__pb2.TransactionChainReport.SerializeToString,
            ),
            'GetAuditTrail': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAuditTrail,
                    request_deserializer=v1_dot_audit_dot_audit__pb2.GetAuditTrailRequest.FromString,
                    response_serializer=v1_dot_audit_dot_audit__pb2.AuditEntry.SerializeToString,
            ),
            'GetAuditReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuditReport,
                    request_deserializer=v1_dot_audit_dot_audit__pb2.GetAuditReportRequest.FromString,
                    response_serializer=v1_dot_audit_dot_audit__pb2.GetAuditReportResponse.SerializeToString,
            ),
            'ExportAuditReport': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportAuditReport,
                    request_deserializer=v1_dot_audit_dot_audit__pb2.ExportAuditReportRequest.FromString,
                    response_serializer=v1_dot_audit_dot_audit__pb2.ExportAuditReportResponse.SerializeToString,
            ),
            'GetSigningKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSigningKeys,
                    request_deserializer=v1_dot_audit_dot_audit__pb2.GetSigningKeysRequest.FromString,
                    response_serializer=v1_dot_audit_dot_audit__pb2.GetSigningKeysResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=v1_dot_common_dot_common__pb2.HealthRequest.FromString,
                    response_serializer=v1_dot_common_dot_common__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ussd.v1.audit.AuditService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ussd.v1.audit.AuditService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuditService(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - AUDIT SERVICE (v1)
    =============================================================================
    Bounded Context: Audit & Integrity
    Responsibility: Tamper-evident audit log, Merkle proofs, cryptographic batch
    integrity verification, hash chain validation, and signed audit reports.
    Language: Rust (cryptographic performance).
    =============================================================================

    """

    @staticmethod
    def GetMerkleProof(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.audit.AuditService/GetMerkleProof',
            v1_dot_audit_dot_audit__pb2.GetMerkleProofRequest.SerializeToString,
            v1_dot_audit_dot_audit__pb2.GetMerkleProofResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLedgerChecksum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.audit.AuditService/GetLedgerChecksum',
            v1_dot_audit_dot_audit__pb2.GetLedgerChecksumRequest.SerializeToString,
            v1_dot_audit_dot_audit__pb2.GetLedgerChecksumResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyBatchIntegrity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.audit.AuditService/VerifyBatchIntegrity',
            v1_dot_audit_dot_audit__pb2.VerifyBatchIntegrityRequest.SerializeToString,
            v1_dot_audit_dot_audit__pb2.VerifyBatchIntegrityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAuditEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ussd.v1.audit.AuditService/StreamAuditEvents',
            v1_dot_audit_dot_audit__pb2.StreamAuditEventsRequest.SerializeToString,
            v1_dot_common_dot_common__pb2.EventEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyTransactionChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.audit.AuditService/VerifyTransactionChain',
            v1_dot_audit_dot_audit__pb2.VerifyTransactionChainRequest.SerializeToString,
            v1_dot_audit_dot_audit__pb2.TransactionChainReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuditTrail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ussd.v1.audit.AuditService/GetAuditTrail',
            v1_dot_audit_dot_audit__pb2.GetAuditTrailRequest.SerializeToString,
            v1_dot_audit_dot_audit__pb2.AuditEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuditReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.audit.AuditService/GetAuditReport',
            v1_dot_audit_dot_audit__pb2.GetAuditReportRequest.SerializeToString,
            v1_dot_audit_dot_audit__pb2.GetAuditReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportAuditReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.audit.AuditService/ExportAuditReport',
            v1_dot_audit_dot_audit__pb2.ExportAuditReportRequest.SerializeToString,
            v1_dot_audit_dot_audit__pb2.ExportAuditReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSigningKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.audit.AuditService/GetSigningKeys',
            v1_dot_audit_dot_audit__pb2.GetSigningKeysRequest.SerializeToString,
            v1_dot_audit_dot_audit__pb2.GetSigningKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.audit.AuditService/Health',
            v1_dot_common_dot_common__pb2.HealthRequest.SerializeToString,
            v1_dot_common_dot_common__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
