apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: session-reconstructor-pdb
  namespace: open-ai-ussd-kernel
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: session-reconstructor
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payment-engine-pdb
  namespace: open-ai-ussd-kernel
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: payment-engine
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: go-orchestrator-pdb
  namespace: open-ai-ussd-kernel
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: go-orchestrator
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: python-gateway-pdb
  namespace: open-ai-ussd-kernel
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: python-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-pdb
  namespace: open-ai-ussd-kernel
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis-pdb
  namespace: open-ai-ussd-kernel
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
