# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from openai_ussd_kernel.protos.v1.common import common_pb2 as v1_dot_common_dot_common__pb2
from openai_ussd_kernel.protos.v1.webhook import webhook_pb2 as v1_dot_webhook_dot_webhook__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in v1/webhook/webhook_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WebhookServiceStub(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - WEBHOOK SERVICE (v1)
    =============================================================================
    Bounded Context: Event Delivery
    Responsibility: Tenant webhook registration, event delivery, retry
    management, delivery logs, and replay.
    Language: Go / Python.
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWebhook = channel.unary_unary(
                '/ussd.v1.webhook.WebhookService/RegisterWebhook',
                request_serializer=v1_dot_webhook_dot_webhook__pb2.RegisterWebhookRequest.SerializeToString,
                response_deserializer=v1_dot_webhook_dot_webhook__pb2.Webhook.FromString,
                _registered_method=True)
        self.GetWebhook = channel.unary_unary(
                '/ussd.v1.webhook.WebhookService/GetWebhook',
                request_serializer=v1_dot_webhook_dot_webhook__pb2.GetWebhookRequest.SerializeToString,
                response_deserializer=v1_dot_webhook_dot_webhook__pb2.Webhook.FromString,
                _registered_method=True)
        self.ListWebhooks = channel.unary_unary(
                '/ussd.v1.webhook.WebhookService/ListWebhooks',
                request_serializer=v1_dot_webhook_dot_webhook__pb2.ListWebhooksRequest.SerializeToString,
                response_deserializer=v1_dot_webhook_dot_webhook__pb2.ListWebhooksResponse.FromString,
                _registered_method=True)
        self.UpdateWebhook = channel.unary_unary(
                '/ussd.v1.webhook.WebhookService/UpdateWebhook',
                request_serializer=v1_dot_webhook_dot_webhook__pb2.UpdateWebhookRequest.SerializeToString,
                response_deserializer=v1_dot_webhook_dot_webhook__pb2.Webhook.FromString,
                _registered_method=True)
        self.DeleteWebhook = channel.unary_unary(
                '/ussd.v1.webhook.WebhookService/DeleteWebhook',
                request_serializer=v1_dot_webhook_dot_webhook__pb2.DeleteWebhookRequest.SerializeToString,
                response_deserializer=v1_dot_webhook_dot_webhook__pb2.DeleteWebhookResponse.FromString,
                _registered_method=True)
        self.DeliverEvent = channel.unary_unary(
                '/ussd.v1.webhook.WebhookService/DeliverEvent',
                request_serializer=v1_dot_webhook_dot_webhook__pb2.DeliverEventRequest.SerializeToString,
                response_deserializer=v1_dot_webhook_dot_webhook__pb2.DeliveryResponse.FromString,
                _registered_method=True)
        self.GetDeliveryLog = channel.unary_unary(
                '/ussd.v1.webhook.WebhookService/GetDeliveryLog',
                request_serializer=v1_dot_webhook_dot_webhook__pb2.GetDeliveryLogRequest.SerializeToString,
                response_deserializer=v1_dot_webhook_dot_webhook__pb2.DeliveryLog.FromString,
                _registered_method=True)
        self.ListDeliveryLogs = channel.unary_unary(
                '/ussd.v1.webhook.WebhookService/ListDeliveryLogs',
                request_serializer=v1_dot_webhook_dot_webhook__pb2.ListDeliveryLogsRequest.SerializeToString,
                response_deserializer=v1_dot_webhook_dot_webhook__pb2.ListDeliveryLogsResponse.FromString,
                _registered_method=True)
        self.ReplayEvent = channel.unary_unary(
                '/ussd.v1.webhook.WebhookService/ReplayEvent',
                request_serializer=v1_dot_webhook_dot_webhook__pb2.ReplayEventRequest.SerializeToString,
                response_deserializer=v1_dot_webhook_dot_webhook__pb2.DeliveryResponse.FromString,
                _registered_method=True)
        self.TestWebhook = channel.unary_unary(
                '/ussd.v1.webhook.WebhookService/TestWebhook',
                request_serializer=v1_dot_webhook_dot_webhook__pb2.TestWebhookRequest.SerializeToString,
                response_deserializer=v1_dot_webhook_dot_webhook__pb2.DeliveryResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ussd.v1.webhook.WebhookService/Health',
                request_serializer=v1_dot_common_dot_common__pb2.HealthRequest.SerializeToString,
                response_deserializer=v1_dot_common_dot_common__pb2.HealthResponse.FromString,
                _registered_method=True)


class WebhookServiceServicer(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - WEBHOOK SERVICE (v1)
    =============================================================================
    Bounded Context: Event Delivery
    Responsibility: Tenant webhook registration, event delivery, retry
    management, delivery logs, and replay.
    Language: Go / Python.
    =============================================================================

    """

    def RegisterWebhook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWebhook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWebhooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWebhook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteWebhook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeliverEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeliveryLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDeliveryLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplayEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestWebhook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WebhookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWebhook': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWebhook,
                    request_deserializer=v1_dot_webhook_dot_webhook__pb2.RegisterWebhookRequest.FromString,
                    response_serializer=v1_dot_webhook_dot_webhook__pb2.Webhook.SerializeToString,
            ),
            'GetWebhook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWebhook,
                    request_deserializer=v1_dot_webhook_dot_webhook__pb2.GetWebhookRequest.FromString,
                    response_serializer=v1_dot_webhook_dot_webhook__pb2.Webhook.SerializeToString,
            ),
            'ListWebhooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWebhooks,
                    request_deserializer=v1_dot_webhook_dot_webhook__pb2.ListWebhooksRequest.FromString,
                    response_serializer=v1_dot_webhook_dot_webhook__pb2.ListWebhooksResponse.SerializeToString,
            ),
            'UpdateWebhook': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWebhook,
                    request_deserializer=v1_dot_webhook_dot_webhook__pb2.UpdateWebhookRequest.FromString,
                    response_serializer=v1_dot_webhook_dot_webhook__pb2.Webhook.SerializeToString,
            ),
            'DeleteWebhook': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteWebhook,
                    request_deserializer=v1_dot_webhook_dot_webhook__pb2.DeleteWebhookRequest.FromString,
                    response_serializer=v1_dot_webhook_dot_webhook__pb2.DeleteWebhookResponse.SerializeToString,
            ),
            'DeliverEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeliverEvent,
                    request_deserializer=v1_dot_webhook_dot_webhook__pb2.DeliverEventRequest.FromString,
                    response_serializer=v1_dot_webhook_dot_webhook__pb2.DeliveryResponse.SerializeToString,
            ),
            'GetDeliveryLog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeliveryLog,
                    request_deserializer=v1_dot_webhook_dot_webhook__pb2.GetDeliveryLogRequest.FromString,
                    response_serializer=v1_dot_webhook_dot_webhook__pb2.DeliveryLog.SerializeToString,
            ),
            'ListDeliveryLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDeliveryLogs,
                    request_deserializer=v1_dot_webhook_dot_webhook__pb2.ListDeliveryLogsRequest.FromString,
                    response_serializer=v1_dot_webhook_dot_webhook__pb2.ListDeliveryLogsResponse.SerializeToString,
            ),
            'ReplayEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplayEvent,
                    request_deserializer=v1_dot_webhook_dot_webhook__pb2.ReplayEventRequest.FromString,
                    response_serializer=v1_dot_webhook_dot_webhook__pb2.DeliveryResponse.SerializeToString,
            ),
            'TestWebhook': grpc.unary_unary_rpc_method_handler(
                    servicer.TestWebhook,
                    request_deserializer=v1_dot_webhook_dot_webhook__pb2.TestWebhookRequest.FromString,
                    response_serializer=v1_dot_webhook_dot_webhook__pb2.DeliveryResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=v1_dot_common_dot_common__pb2.HealthRequest.FromString,
                    response_serializer=v1_dot_common_dot_common__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ussd.v1.webhook.WebhookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ussd.v1.webhook.WebhookService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WebhookService(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - WEBHOOK SERVICE (v1)
    =============================================================================
    Bounded Context: Event Delivery
    Responsibility: Tenant webhook registration, event delivery, retry
    management, delivery logs, and replay.
    Language: Go / Python.
    =============================================================================

    """

    @staticmethod
    def RegisterWebhook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.webhook.WebhookService/RegisterWebhook',
            v1_dot_webhook_dot_webhook__pb2.RegisterWebhookRequest.SerializeToString,
            v1_dot_webhook_dot_webhook__pb2.Webhook.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWebhook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.webhook.WebhookService/GetWebhook',
            v1_dot_webhook_dot_webhook__pb2.GetWebhookRequest.SerializeToString,
            v1_dot_webhook_dot_webhook__pb2.Webhook.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWebhooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.webhook.WebhookService/ListWebhooks',
            v1_dot_webhook_dot_webhook__pb2.ListWebhooksRequest.SerializeToString,
            v1_dot_webhook_dot_webhook__pb2.ListWebhooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateWebhook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.webhook.WebhookService/UpdateWebhook',
            v1_dot_webhook_dot_webhook__pb2.UpdateWebhookRequest.SerializeToString,
            v1_dot_webhook_dot_webhook__pb2.Webhook.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteWebhook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.webhook.WebhookService/DeleteWebhook',
            v1_dot_webhook_dot_webhook__pb2.DeleteWebhookRequest.SerializeToString,
            v1_dot_webhook_dot_webhook__pb2.DeleteWebhookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeliverEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.webhook.WebhookService/DeliverEvent',
            v1_dot_webhook_dot_webhook__pb2.DeliverEventRequest.SerializeToString,
            v1_dot_webhook_dot_webhook__pb2.DeliveryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeliveryLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.webhook.WebhookService/GetDeliveryLog',
            v1_dot_webhook_dot_webhook__pb2.GetDeliveryLogRequest.SerializeToString,
            v1_dot_webhook_dot_webhook__pb2.DeliveryLog.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDeliveryLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.webhook.WebhookService/ListDeliveryLogs',
            v1_dot_webhook_dot_webhook__pb2.ListDeliveryLogsRequest.SerializeToString,
            v1_dot_webhook_dot_webhook__pb2.ListDeliveryLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplayEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.webhook.WebhookService/ReplayEvent',
            v1_dot_webhook_dot_webhook__pb2.ReplayEventRequest.SerializeToString,
            v1_dot_webhook_dot_webhook__pb2.DeliveryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestWebhook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.webhook.WebhookService/TestWebhook',
            v1_dot_webhook_dot_webhook__pb2.TestWebhookRequest.SerializeToString,
            v1_dot_webhook_dot_webhook__pb2.DeliveryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.webhook.WebhookService/Health',
            v1_dot_common_dot_common__pb2.HealthRequest.SerializeToString,
            v1_dot_common_dot_common__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
