# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from openai_ussd_kernel.protos.v1.admin import admin_pb2 as v1_dot_admin_dot_admin__pb2
from openai_ussd_kernel.protos.v1.common import common_pb2 as v1_dot_common_dot_common__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in v1/admin/admin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdminServiceStub(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - ADMIN SERVICE (v1)
    =============================================================================
    Bounded Context: System Operations
    Responsibility: System-level administration, metrics, cache management,
    dead letter queue operations, key rotation, projection rebuilds, and backups.
    Language: Go.
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSystemStatus = channel.unary_unary(
                '/ussd.v1.admin.AdminService/GetSystemStatus',
                request_serializer=v1_dot_admin_dot_admin__pb2.GetSystemStatusRequest.SerializeToString,
                response_deserializer=v1_dot_admin_dot_admin__pb2.SystemStatus.FromString,
                _registered_method=True)
        self.GetServiceMetrics = channel.unary_unary(
                '/ussd.v1.admin.AdminService/GetServiceMetrics',
                request_serializer=v1_dot_admin_dot_admin__pb2.GetServiceMetricsRequest.SerializeToString,
                response_deserializer=v1_dot_admin_dot_admin__pb2.ServiceMetricsResponse.FromString,
                _registered_method=True)
        self.GetCacheStatus = channel.unary_unary(
                '/ussd.v1.admin.AdminService/GetCacheStatus',
                request_serializer=v1_dot_admin_dot_admin__pb2.GetCacheStatusRequest.SerializeToString,
                response_deserializer=v1_dot_admin_dot_admin__pb2.CacheStatusResponse.FromString,
                _registered_method=True)
        self.InvalidateCache = channel.unary_unary(
                '/ussd.v1.admin.AdminService/InvalidateCache',
                request_serializer=v1_dot_admin_dot_admin__pb2.InvalidateCacheRequest.SerializeToString,
                response_deserializer=v1_dot_admin_dot_admin__pb2.InvalidateCacheResponse.FromString,
                _registered_method=True)
        self.GetDeadLetterQueue = channel.unary_unary(
                '/ussd.v1.admin.AdminService/GetDeadLetterQueue',
                request_serializer=v1_dot_admin_dot_admin__pb2.GetDeadLetterQueueRequest.SerializeToString,
                response_deserializer=v1_dot_admin_dot_admin__pb2.GetDeadLetterQueueResponse.FromString,
                _registered_method=True)
        self.ReplayDeadLetter = channel.unary_unary(
                '/ussd.v1.admin.AdminService/ReplayDeadLetter',
                request_serializer=v1_dot_admin_dot_admin__pb2.ReplayDeadLetterRequest.SerializeToString,
                response_deserializer=v1_dot_admin_dot_admin__pb2.ReplayDeadLetterResponse.FromString,
                _registered_method=True)
        self.PurgeDeadLetter = channel.unary_unary(
                '/ussd.v1.admin.AdminService/PurgeDeadLetter',
                request_serializer=v1_dot_admin_dot_admin__pb2.PurgeDeadLetterRequest.SerializeToString,
                response_deserializer=v1_dot_admin_dot_admin__pb2.PurgeDeadLetterResponse.FromString,
                _registered_method=True)
        self.TriggerReconciliation = channel.unary_unary(
                '/ussd.v1.admin.AdminService/TriggerReconciliation',
                request_serializer=v1_dot_admin_dot_admin__pb2.TriggerReconciliationRequest.SerializeToString,
                response_deserializer=v1_dot_admin_dot_admin__pb2.TriggerReconciliationResponse.FromString,
                _registered_method=True)
        self.RotateSigningKey = channel.unary_unary(
                '/ussd.v1.admin.AdminService/RotateSigningKey',
                request_serializer=v1_dot_admin_dot_admin__pb2.RotateSigningKeyRequest.SerializeToString,
                response_deserializer=v1_dot_admin_dot_admin__pb2.RotateSigningKeyResponse.FromString,
                _registered_method=True)
        self.PurgeOldSessions = channel.unary_unary(
                '/ussd.v1.admin.AdminService/PurgeOldSessions',
                request_serializer=v1_dot_admin_dot_admin__pb2.PurgeOldSessionsRequest.SerializeToString,
                response_deserializer=v1_dot_admin_dot_admin__pb2.PurgeOldSessionsResponse.FromString,
                _registered_method=True)
        self.RebuildProjection = channel.unary_unary(
                '/ussd.v1.admin.AdminService/RebuildProjection',
                request_serializer=v1_dot_admin_dot_admin__pb2.RebuildProjectionRequest.SerializeToString,
                response_deserializer=v1_dot_admin_dot_admin__pb2.RebuildProjectionResponse.FromString,
                _registered_method=True)
        self.BackupLedger = channel.unary_unary(
                '/ussd.v1.admin.AdminService/BackupLedger',
                request_serializer=v1_dot_admin_dot_admin__pb2.BackupLedgerRequest.SerializeToString,
                response_deserializer=v1_dot_admin_dot_admin__pb2.BackupLedgerResponse.FromString,
                _registered_method=True)
        self.GetSystemConfig = channel.unary_unary(
                '/ussd.v1.admin.AdminService/GetSystemConfig',
                request_serializer=v1_dot_admin_dot_admin__pb2.GetSystemConfigRequest.SerializeToString,
                response_deserializer=v1_dot_admin_dot_admin__pb2.SystemConfig.FromString,
                _registered_method=True)
        self.UpdateSystemConfig = channel.unary_unary(
                '/ussd.v1.admin.AdminService/UpdateSystemConfig',
                request_serializer=v1_dot_admin_dot_admin__pb2.UpdateSystemConfigRequest.SerializeToString,
                response_deserializer=v1_dot_admin_dot_admin__pb2.SystemConfig.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ussd.v1.admin.AdminService/Health',
                request_serializer=v1_dot_common_dot_common__pb2.HealthRequest.SerializeToString,
                response_deserializer=v1_dot_common_dot_common__pb2.HealthResponse.FromString,
                _registered_method=True)


class AdminServiceServicer(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - ADMIN SERVICE (v1)
    =============================================================================
    Bounded Context: System Operations
    Responsibility: System-level administration, metrics, cache management,
    dead letter queue operations, key rotation, projection rebuilds, and backups.
    Language: Go.
    =============================================================================

    """

    def GetSystemStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCacheStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvalidateCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeadLetterQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplayDeadLetter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurgeDeadLetter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerReconciliation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RotateSigningKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurgeOldSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RebuildProjection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BackupLedger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSystemConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSystemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStatus,
                    request_deserializer=v1_dot_admin_dot_admin__pb2.GetSystemStatusRequest.FromString,
                    response_serializer=v1_dot_admin_dot_admin__pb2.SystemStatus.SerializeToString,
            ),
            'GetServiceMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceMetrics,
                    request_deserializer=v1_dot_admin_dot_admin__pb2.GetServiceMetricsRequest.FromString,
                    response_serializer=v1_dot_admin_dot_admin__pb2.ServiceMetricsResponse.SerializeToString,
            ),
            'GetCacheStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCacheStatus,
                    request_deserializer=v1_dot_admin_dot_admin__pb2.GetCacheStatusRequest.FromString,
                    response_serializer=v1_dot_admin_dot_admin__pb2.CacheStatusResponse.SerializeToString,
            ),
            'InvalidateCache': grpc.unary_unary_rpc_method_handler(
                    servicer.InvalidateCache,
                    request_deserializer=v1_dot_admin_dot_admin__pb2.InvalidateCacheRequest.FromString,
                    response_serializer=v1_dot_admin_dot_admin__pb2.InvalidateCacheResponse.SerializeToString,
            ),
            'GetDeadLetterQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeadLetterQueue,
                    request_deserializer=v1_dot_admin_dot_admin__pb2.GetDeadLetterQueueRequest.FromString,
                    response_serializer=v1_dot_admin_dot_admin__pb2.GetDeadLetterQueueResponse.SerializeToString,
            ),
            'ReplayDeadLetter': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplayDeadLetter,
                    request_deserializer=v1_dot_admin_dot_admin__pb2.ReplayDeadLetterRequest.FromString,
                    response_serializer=v1_dot_admin_dot_admin__pb2.ReplayDeadLetterResponse.SerializeToString,
            ),
            'PurgeDeadLetter': grpc.unary_unary_rpc_method_handler(
                    servicer.PurgeDeadLetter,
                    request_deserializer=v1_dot_admin_dot_admin__pb2.PurgeDeadLetterRequest.FromString,
                    response_serializer=v1_dot_admin_dot_admin__pb2.PurgeDeadLetterResponse.SerializeToString,
            ),
            'TriggerReconciliation': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerReconciliation,
                    request_deserializer=v1_dot_admin_dot_admin__pb2.TriggerReconciliationRequest.FromString,
                    response_serializer=v1_dot_admin_dot_admin__pb2.TriggerReconciliationResponse.SerializeToString,
            ),
            'RotateSigningKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RotateSigningKey,
                    request_deserializer=v1_dot_admin_dot_admin__pb2.RotateSigningKeyRequest.FromString,
                    response_serializer=v1_dot_admin_dot_admin__pb2.RotateSigningKeyResponse.SerializeToString,
            ),
            'PurgeOldSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.PurgeOldSessions,
                    request_deserializer=v1_dot_admin_dot_admin__pb2.PurgeOldSessionsRequest.FromString,
                    response_serializer=v1_dot_admin_dot_admin__pb2.PurgeOldSessionsResponse.SerializeToString,
            ),
            'RebuildProjection': grpc.unary_unary_rpc_method_handler(
                    servicer.RebuildProjection,
                    request_deserializer=v1_dot_admin_dot_admin__pb2.RebuildProjectionRequest.FromString,
                    response_serializer=v1_dot_admin_dot_admin__pb2.RebuildProjectionResponse.SerializeToString,
            ),
            'BackupLedger': grpc.unary_unary_rpc_method_handler(
                    servicer.BackupLedger,
                    request_deserializer=v1_dot_admin_dot_admin__pb2.BackupLedgerRequest.FromString,
                    response_serializer=v1_dot_admin_dot_admin__pb2.BackupLedgerResponse.SerializeToString,
            ),
            'GetSystemConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemConfig,
                    request_deserializer=v1_dot_admin_dot_admin__pb2.GetSystemConfigRequest.FromString,
                    response_serializer=v1_dot_admin_dot_admin__pb2.SystemConfig.SerializeToString,
            ),
            'UpdateSystemConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSystemConfig,
                    request_deserializer=v1_dot_admin_dot_admin__pb2.UpdateSystemConfigRequest.FromString,
                    response_serializer=v1_dot_admin_dot_admin__pb2.SystemConfig.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=v1_dot_common_dot_common__pb2.HealthRequest.FromString,
                    response_serializer=v1_dot_common_dot_common__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ussd.v1.admin.AdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ussd.v1.admin.AdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminService(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - ADMIN SERVICE (v1)
    =============================================================================
    Bounded Context: System Operations
    Responsibility: System-level administration, metrics, cache management,
    dead letter queue operations, key rotation, projection rebuilds, and backups.
    Language: Go.
    =============================================================================

    """

    @staticmethod
    def GetSystemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.admin.AdminService/GetSystemStatus',
            v1_dot_admin_dot_admin__pb2.GetSystemStatusRequest.SerializeToString,
            v1_dot_admin_dot_admin__pb2.SystemStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.admin.AdminService/GetServiceMetrics',
            v1_dot_admin_dot_admin__pb2.GetServiceMetricsRequest.SerializeToString,
            v1_dot_admin_dot_admin__pb2.ServiceMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCacheStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.admin.AdminService/GetCacheStatus',
            v1_dot_admin_dot_admin__pb2.GetCacheStatusRequest.SerializeToString,
            v1_dot_admin_dot_admin__pb2.CacheStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvalidateCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.admin.AdminService/InvalidateCache',
            v1_dot_admin_dot_admin__pb2.InvalidateCacheRequest.SerializeToString,
            v1_dot_admin_dot_admin__pb2.InvalidateCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeadLetterQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.admin.AdminService/GetDeadLetterQueue',
            v1_dot_admin_dot_admin__pb2.GetDeadLetterQueueRequest.SerializeToString,
            v1_dot_admin_dot_admin__pb2.GetDeadLetterQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplayDeadLetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.admin.AdminService/ReplayDeadLetter',
            v1_dot_admin_dot_admin__pb2.ReplayDeadLetterRequest.SerializeToString,
            v1_dot_admin_dot_admin__pb2.ReplayDeadLetterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PurgeDeadLetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.admin.AdminService/PurgeDeadLetter',
            v1_dot_admin_dot_admin__pb2.PurgeDeadLetterRequest.SerializeToString,
            v1_dot_admin_dot_admin__pb2.PurgeDeadLetterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerReconciliation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.admin.AdminService/TriggerReconciliation',
            v1_dot_admin_dot_admin__pb2.TriggerReconciliationRequest.SerializeToString,
            v1_dot_admin_dot_admin__pb2.TriggerReconciliationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RotateSigningKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.admin.AdminService/RotateSigningKey',
            v1_dot_admin_dot_admin__pb2.RotateSigningKeyRequest.SerializeToString,
            v1_dot_admin_dot_admin__pb2.RotateSigningKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PurgeOldSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.admin.AdminService/PurgeOldSessions',
            v1_dot_admin_dot_admin__pb2.PurgeOldSessionsRequest.SerializeToString,
            v1_dot_admin_dot_admin__pb2.PurgeOldSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RebuildProjection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.admin.AdminService/RebuildProjection',
            v1_dot_admin_dot_admin__pb2.RebuildProjectionRequest.SerializeToString,
            v1_dot_admin_dot_admin__pb2.RebuildProjectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BackupLedger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.admin.AdminService/BackupLedger',
            v1_dot_admin_dot_admin__pb2.BackupLedgerRequest.SerializeToString,
            v1_dot_admin_dot_admin__pb2.BackupLedgerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.admin.AdminService/GetSystemConfig',
            v1_dot_admin_dot_admin__pb2.GetSystemConfigRequest.SerializeToString,
            v1_dot_admin_dot_admin__pb2.SystemConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSystemConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.admin.AdminService/UpdateSystemConfig',
            v1_dot_admin_dot_admin__pb2.UpdateSystemConfigRequest.SerializeToString,
            v1_dot_admin_dot_admin__pb2.SystemConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.admin.AdminService/Health',
            v1_dot_common_dot_common__pb2.HealthRequest.SerializeToString,
            v1_dot_common_dot_common__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
