# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from openai_ussd_kernel.protos.v1.common import common_pb2 as v1_dot_common_dot_common__pb2
from openai_ussd_kernel.protos.v1.session import session_pb2 as v1_dot_session_dot_session__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in v1/session/session_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SessionReconstructorStub(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - SESSION RECONSTRUCTOR SERVICE (v1)
    =============================================================================
    Bounded Context: Session Management
    Responsibility: Event-sourced session state reconstruction, integrity
    verification, checkpoint/restore, and concurrent session handling.
    Language: Rust (high-performance replay and Merkle proofs).
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReconstructSession = channel.unary_unary(
                '/ussd.v1.session.SessionReconstructor/ReconstructSession',
                request_serializer=v1_dot_session_dot_session__pb2.ReconstructSessionRequest.SerializeToString,
                response_deserializer=v1_dot_session_dot_session__pb2.ReconstructSessionResponse.FromString,
                _registered_method=True)
        self.ReconstructSessions = channel.stream_stream(
                '/ussd.v1.session.SessionReconstructor/ReconstructSessions',
                request_serializer=v1_dot_session_dot_session__pb2.ReconstructSessionRequest.SerializeToString,
                response_deserializer=v1_dot_session_dot_session__pb2.ReconstructSessionResponse.FromString,
                _registered_method=True)
        self.GetSessionEvents = channel.unary_stream(
                '/ussd.v1.session.SessionReconstructor/GetSessionEvents',
                request_serializer=v1_dot_session_dot_session__pb2.GetSessionEventsRequest.SerializeToString,
                response_deserializer=v1_dot_session_dot_session__pb2.SessionEvent.FromString,
                _registered_method=True)
        self.VerifySessionIntegrity = channel.unary_unary(
                '/ussd.v1.session.SessionReconstructor/VerifySessionIntegrity',
                request_serializer=v1_dot_session_dot_session__pb2.VerifySessionRequest.SerializeToString,
                response_deserializer=v1_dot_session_dot_session__pb2.VerifySessionResponse.FromString,
                _registered_method=True)
        self.GetIntegrityProof = channel.unary_unary(
                '/ussd.v1.session.SessionReconstructor/GetIntegrityProof',
                request_serializer=v1_dot_session_dot_session__pb2.GetIntegrityProofRequest.SerializeToString,
                response_deserializer=v1_dot_session_dot_session__pb2.IntegrityProof.FromString,
                _registered_method=True)
        self.CreateCheckpoint = channel.unary_unary(
                '/ussd.v1.session.SessionReconstructor/CreateCheckpoint',
                request_serializer=v1_dot_session_dot_session__pb2.CreateCheckpointRequest.SerializeToString,
                response_deserializer=v1_dot_session_dot_session__pb2.CreateCheckpointResponse.FromString,
                _registered_method=True)
        self.RestoreCheckpoint = channel.unary_unary(
                '/ussd.v1.session.SessionReconstructor/RestoreCheckpoint',
                request_serializer=v1_dot_session_dot_session__pb2.RestoreCheckpointRequest.SerializeToString,
                response_deserializer=v1_dot_session_dot_session__pb2.RestoreCheckpointResponse.FromString,
                _registered_method=True)
        self.ListActiveSessions = channel.unary_unary(
                '/ussd.v1.session.SessionReconstructor/ListActiveSessions',
                request_serializer=v1_dot_session_dot_session__pb2.ListActiveSessionsRequest.SerializeToString,
                response_deserializer=v1_dot_session_dot_session__pb2.ListActiveSessionsResponse.FromString,
                _registered_method=True)
        self.SearchSessions = channel.unary_unary(
                '/ussd.v1.session.SessionReconstructor/SearchSessions',
                request_serializer=v1_dot_session_dot_session__pb2.SearchSessionsRequest.SerializeToString,
                response_deserializer=v1_dot_session_dot_session__pb2.SearchSessionsResponse.FromString,
                _registered_method=True)
        self.GetConcurrentSessions = channel.unary_unary(
                '/ussd.v1.session.SessionReconstructor/GetConcurrentSessions',
                request_serializer=v1_dot_session_dot_session__pb2.GetConcurrentSessionsRequest.SerializeToString,
                response_deserializer=v1_dot_session_dot_session__pb2.GetConcurrentSessionsResponse.FromString,
                _registered_method=True)
        self.MergeSessions = channel.unary_unary(
                '/ussd.v1.session.SessionReconstructor/MergeSessions',
                request_serializer=v1_dot_session_dot_session__pb2.MergeSessionsRequest.SerializeToString,
                response_deserializer=v1_dot_session_dot_session__pb2.MergeSessionsResponse.FromString,
                _registered_method=True)
        self.GetSessionMetrics = channel.unary_unary(
                '/ussd.v1.session.SessionReconstructor/GetSessionMetrics',
                request_serializer=v1_dot_session_dot_session__pb2.GetSessionMetricsRequest.SerializeToString,
                response_deserializer=v1_dot_session_dot_session__pb2.GetSessionMetricsResponse.FromString,
                _registered_method=True)
        self.InvalidateCache = channel.unary_unary(
                '/ussd.v1.session.SessionReconstructor/InvalidateCache',
                request_serializer=v1_dot_session_dot_session__pb2.InvalidateCacheRequest.SerializeToString,
                response_deserializer=v1_dot_common_dot_common__pb2.Empty.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ussd.v1.session.SessionReconstructor/Health',
                request_serializer=v1_dot_common_dot_common__pb2.HealthRequest.SerializeToString,
                response_deserializer=v1_dot_common_dot_common__pb2.HealthResponse.FromString,
                _registered_method=True)


class SessionReconstructorServicer(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - SESSION RECONSTRUCTOR SERVICE (v1)
    =============================================================================
    Bounded Context: Session Management
    Responsibility: Event-sourced session state reconstruction, integrity
    verification, checkpoint/restore, and concurrent session handling.
    Language: Rust (high-performance replay and Merkle proofs).
    =============================================================================

    """

    def ReconstructSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReconstructSessions(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifySessionIntegrity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIntegrityProof(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListActiveSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConcurrentSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MergeSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvalidateCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionReconstructorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReconstructSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ReconstructSession,
                    request_deserializer=v1_dot_session_dot_session__pb2.ReconstructSessionRequest.FromString,
                    response_serializer=v1_dot_session_dot_session__pb2.ReconstructSessionResponse.SerializeToString,
            ),
            'ReconstructSessions': grpc.stream_stream_rpc_method_handler(
                    servicer.ReconstructSessions,
                    request_deserializer=v1_dot_session_dot_session__pb2.ReconstructSessionRequest.FromString,
                    response_serializer=v1_dot_session_dot_session__pb2.ReconstructSessionResponse.SerializeToString,
            ),
            'GetSessionEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSessionEvents,
                    request_deserializer=v1_dot_session_dot_session__pb2.GetSessionEventsRequest.FromString,
                    response_serializer=v1_dot_session_dot_session__pb2.SessionEvent.SerializeToString,
            ),
            'VerifySessionIntegrity': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifySessionIntegrity,
                    request_deserializer=v1_dot_session_dot_session__pb2.VerifySessionRequest.FromString,
                    response_serializer=v1_dot_session_dot_session__pb2.VerifySessionResponse.SerializeToString,
            ),
            'GetIntegrityProof': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIntegrityProof,
                    request_deserializer=v1_dot_session_dot_session__pb2.GetIntegrityProofRequest.FromString,
                    response_serializer=v1_dot_session_dot_session__pb2.IntegrityProof.SerializeToString,
            ),
            'CreateCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCheckpoint,
                    request_deserializer=v1_dot_session_dot_session__pb2.CreateCheckpointRequest.FromString,
                    response_serializer=v1_dot_session_dot_session__pb2.CreateCheckpointResponse.SerializeToString,
            ),
            'RestoreCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreCheckpoint,
                    request_deserializer=v1_dot_session_dot_session__pb2.RestoreCheckpointRequest.FromString,
                    response_serializer=v1_dot_session_dot_session__pb2.RestoreCheckpointResponse.SerializeToString,
            ),
            'ListActiveSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListActiveSessions,
                    request_deserializer=v1_dot_session_dot_session__pb2.ListActiveSessionsRequest.FromString,
                    response_serializer=v1_dot_session_dot_session__pb2.ListActiveSessionsResponse.SerializeToString,
            ),
            'SearchSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchSessions,
                    request_deserializer=v1_dot_session_dot_session__pb2.SearchSessionsRequest.FromString,
                    response_serializer=v1_dot_session_dot_session__pb2.SearchSessionsResponse.SerializeToString,
            ),
            'GetConcurrentSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConcurrentSessions,
                    request_deserializer=v1_dot_session_dot_session__pb2.GetConcurrentSessionsRequest.FromString,
                    response_serializer=v1_dot_session_dot_session__pb2.GetConcurrentSessionsResponse.SerializeToString,
            ),
            'MergeSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.MergeSessions,
                    request_deserializer=v1_dot_session_dot_session__pb2.MergeSessionsRequest.FromString,
                    response_serializer=v1_dot_session_dot_session__pb2.MergeSessionsResponse.SerializeToString,
            ),
            'GetSessionMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionMetrics,
                    request_deserializer=v1_dot_session_dot_session__pb2.GetSessionMetricsRequest.FromString,
                    response_serializer=v1_dot_session_dot_session__pb2.GetSessionMetricsResponse.SerializeToString,
            ),
            'InvalidateCache': grpc.unary_unary_rpc_method_handler(
                    servicer.InvalidateCache,
                    request_deserializer=v1_dot_session_dot_session__pb2.InvalidateCacheRequest.FromString,
                    response_serializer=v1_dot_common_dot_common__pb2.Empty.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=v1_dot_common_dot_common__pb2.HealthRequest.FromString,
                    response_serializer=v1_dot_common_dot_common__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ussd.v1.session.SessionReconstructor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ussd.v1.session.SessionReconstructor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionReconstructor(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - SESSION RECONSTRUCTOR SERVICE (v1)
    =============================================================================
    Bounded Context: Session Management
    Responsibility: Event-sourced session state reconstruction, integrity
    verification, checkpoint/restore, and concurrent session handling.
    Language: Rust (high-performance replay and Merkle proofs).
    =============================================================================

    """

    @staticmethod
    def ReconstructSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.session.SessionReconstructor/ReconstructSession',
            v1_dot_session_dot_session__pb2.ReconstructSessionRequest.SerializeToString,
            v1_dot_session_dot_session__pb2.ReconstructSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReconstructSessions(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ussd.v1.session.SessionReconstructor/ReconstructSessions',
            v1_dot_session_dot_session__pb2.ReconstructSessionRequest.SerializeToString,
            v1_dot_session_dot_session__pb2.ReconstructSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ussd.v1.session.SessionReconstructor/GetSessionEvents',
            v1_dot_session_dot_session__pb2.GetSessionEventsRequest.SerializeToString,
            v1_dot_session_dot_session__pb2.SessionEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifySessionIntegrity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.session.SessionReconstructor/VerifySessionIntegrity',
            v1_dot_session_dot_session__pb2.VerifySessionRequest.SerializeToString,
            v1_dot_session_dot_session__pb2.VerifySessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIntegrityProof(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.session.SessionReconstructor/GetIntegrityProof',
            v1_dot_session_dot_session__pb2.GetIntegrityProofRequest.SerializeToString,
            v1_dot_session_dot_session__pb2.IntegrityProof.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.session.SessionReconstructor/CreateCheckpoint',
            v1_dot_session_dot_session__pb2.CreateCheckpointRequest.SerializeToString,
            v1_dot_session_dot_session__pb2.CreateCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.session.SessionReconstructor/RestoreCheckpoint',
            v1_dot_session_dot_session__pb2.RestoreCheckpointRequest.SerializeToString,
            v1_dot_session_dot_session__pb2.RestoreCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListActiveSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.session.SessionReconstructor/ListActiveSessions',
            v1_dot_session_dot_session__pb2.ListActiveSessionsRequest.SerializeToString,
            v1_dot_session_dot_session__pb2.ListActiveSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.session.SessionReconstructor/SearchSessions',
            v1_dot_session_dot_session__pb2.SearchSessionsRequest.SerializeToString,
            v1_dot_session_dot_session__pb2.SearchSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConcurrentSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.session.SessionReconstructor/GetConcurrentSessions',
            v1_dot_session_dot_session__pb2.GetConcurrentSessionsRequest.SerializeToString,
            v1_dot_session_dot_session__pb2.GetConcurrentSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MergeSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.session.SessionReconstructor/MergeSessions',
            v1_dot_session_dot_session__pb2.MergeSessionsRequest.SerializeToString,
            v1_dot_session_dot_session__pb2.MergeSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.session.SessionReconstructor/GetSessionMetrics',
            v1_dot_session_dot_session__pb2.GetSessionMetricsRequest.SerializeToString,
            v1_dot_session_dot_session__pb2.GetSessionMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvalidateCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.session.SessionReconstructor/InvalidateCache',
            v1_dot_session_dot_session__pb2.InvalidateCacheRequest.SerializeToString,
            v1_dot_common_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.session.SessionReconstructor/Health',
            v1_dot_common_dot_common__pb2.HealthRequest.SerializeToString,
            v1_dot_common_dot_common__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
