# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from openai_ussd_kernel.protos.v1.common import common_pb2 as v1_dot_common_dot_common__pb2
from openai_ussd_kernel.protos.v1.messaging import messaging_pb2 as v1_dot_messaging_dot_messaging__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in v1/messaging/messaging_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MessagingServiceStub(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - MESSAGING SERVICE (v1)
    =============================================================================
    Bounded Context: Notifications
    Responsibility: SMS, WhatsApp, and email delivery via Africa's Talking and
    other provider adapters. Supports batch messaging and template-based sending.
    Language: Python / Go.
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendSMS = channel.unary_unary(
                '/ussd.v1.messaging.MessagingService/SendSMS',
                request_serializer=v1_dot_messaging_dot_messaging__pb2.SendSMSRequest.SerializeToString,
                response_deserializer=v1_dot_messaging_dot_messaging__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.SendWhatsApp = channel.unary_unary(
                '/ussd.v1.messaging.MessagingService/SendWhatsApp',
                request_serializer=v1_dot_messaging_dot_messaging__pb2.SendWhatsAppRequest.SerializeToString,
                response_deserializer=v1_dot_messaging_dot_messaging__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.SendEmail = channel.unary_unary(
                '/ussd.v1.messaging.MessagingService/SendEmail',
                request_serializer=v1_dot_messaging_dot_messaging__pb2.SendEmailRequest.SerializeToString,
                response_deserializer=v1_dot_messaging_dot_messaging__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.SendBatchMessages = channel.unary_unary(
                '/ussd.v1.messaging.MessagingService/SendBatchMessages',
                request_serializer=v1_dot_messaging_dot_messaging__pb2.SendBatchMessagesRequest.SerializeToString,
                response_deserializer=v1_dot_common_dot_common__pb2.BatchOperationResult.FromString,
                _registered_method=True)
        self.GetMessageStatus = channel.unary_unary(
                '/ussd.v1.messaging.MessagingService/GetMessageStatus',
                request_serializer=v1_dot_messaging_dot_messaging__pb2.GetMessageStatusRequest.SerializeToString,
                response_deserializer=v1_dot_messaging_dot_messaging__pb2.MessageStatusResponse.FromString,
                _registered_method=True)
        self.ListMessages = channel.unary_unary(
                '/ussd.v1.messaging.MessagingService/ListMessages',
                request_serializer=v1_dot_messaging_dot_messaging__pb2.ListMessagesRequest.SerializeToString,
                response_deserializer=v1_dot_messaging_dot_messaging__pb2.ListMessagesResponse.FromString,
                _registered_method=True)
        self.GetMessageTemplate = channel.unary_unary(
                '/ussd.v1.messaging.MessagingService/GetMessageTemplate',
                request_serializer=v1_dot_messaging_dot_messaging__pb2.GetMessageTemplateRequest.SerializeToString,
                response_deserializer=v1_dot_messaging_dot_messaging__pb2.MessageTemplate.FromString,
                _registered_method=True)
        self.ListMessageTemplates = channel.unary_unary(
                '/ussd.v1.messaging.MessagingService/ListMessageTemplates',
                request_serializer=v1_dot_messaging_dot_messaging__pb2.ListMessageTemplatesRequest.SerializeToString,
                response_deserializer=v1_dot_messaging_dot_messaging__pb2.ListMessageTemplatesResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ussd.v1.messaging.MessagingService/Health',
                request_serializer=v1_dot_common_dot_common__pb2.HealthRequest.SerializeToString,
                response_deserializer=v1_dot_common_dot_common__pb2.HealthResponse.FromString,
                _registered_method=True)


class MessagingServiceServicer(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - MESSAGING SERVICE (v1)
    =============================================================================
    Bounded Context: Notifications
    Responsibility: SMS, WhatsApp, and email delivery via Africa's Talking and
    other provider adapters. Supports batch messaging and template-based sending.
    Language: Python / Go.
    =============================================================================

    """

    def SendSMS(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendWhatsApp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendBatchMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessageStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessageTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMessageTemplates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessagingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendSMS': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSMS,
                    request_deserializer=v1_dot_messaging_dot_messaging__pb2.SendSMSRequest.FromString,
                    response_serializer=v1_dot_messaging_dot_messaging__pb2.SendMessageResponse.SerializeToString,
            ),
            'SendWhatsApp': grpc.unary_unary_rpc_method_handler(
                    servicer.SendWhatsApp,
                    request_deserializer=v1_dot_messaging_dot_messaging__pb2.SendWhatsAppRequest.FromString,
                    response_serializer=v1_dot_messaging_dot_messaging__pb2.SendMessageResponse.SerializeToString,
            ),
            'SendEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.SendEmail,
                    request_deserializer=v1_dot_messaging_dot_messaging__pb2.SendEmailRequest.FromString,
                    response_serializer=v1_dot_messaging_dot_messaging__pb2.SendMessageResponse.SerializeToString,
            ),
            'SendBatchMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBatchMessages,
                    request_deserializer=v1_dot_messaging_dot_messaging__pb2.SendBatchMessagesRequest.FromString,
                    response_serializer=v1_dot_common_dot_common__pb2.BatchOperationResult.SerializeToString,
            ),
            'GetMessageStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessageStatus,
                    request_deserializer=v1_dot_messaging_dot_messaging__pb2.GetMessageStatusRequest.FromString,
                    response_serializer=v1_dot_messaging_dot_messaging__pb2.MessageStatusResponse.SerializeToString,
            ),
            'ListMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMessages,
                    request_deserializer=v1_dot_messaging_dot_messaging__pb2.ListMessagesRequest.FromString,
                    response_serializer=v1_dot_messaging_dot_messaging__pb2.ListMessagesResponse.SerializeToString,
            ),
            'GetMessageTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessageTemplate,
                    request_deserializer=v1_dot_messaging_dot_messaging__pb2.GetMessageTemplateRequest.FromString,
                    response_serializer=v1_dot_messaging_dot_messaging__pb2.MessageTemplate.SerializeToString,
            ),
            'ListMessageTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMessageTemplates,
                    request_deserializer=v1_dot_messaging_dot_messaging__pb2.ListMessageTemplatesRequest.FromString,
                    response_serializer=v1_dot_messaging_dot_messaging__pb2.ListMessageTemplatesResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=v1_dot_common_dot_common__pb2.HealthRequest.FromString,
                    response_serializer=v1_dot_common_dot_common__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ussd.v1.messaging.MessagingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ussd.v1.messaging.MessagingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessagingService(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - MESSAGING SERVICE (v1)
    =============================================================================
    Bounded Context: Notifications
    Responsibility: SMS, WhatsApp, and email delivery via Africa's Talking and
    other provider adapters. Supports batch messaging and template-based sending.
    Language: Python / Go.
    =============================================================================

    """

    @staticmethod
    def SendSMS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.messaging.MessagingService/SendSMS',
            v1_dot_messaging_dot_messaging__pb2.SendSMSRequest.SerializeToString,
            v1_dot_messaging_dot_messaging__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendWhatsApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.messaging.MessagingService/SendWhatsApp',
            v1_dot_messaging_dot_messaging__pb2.SendWhatsAppRequest.SerializeToString,
            v1_dot_messaging_dot_messaging__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.messaging.MessagingService/SendEmail',
            v1_dot_messaging_dot_messaging__pb2.SendEmailRequest.SerializeToString,
            v1_dot_messaging_dot_messaging__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendBatchMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.messaging.MessagingService/SendBatchMessages',
            v1_dot_messaging_dot_messaging__pb2.SendBatchMessagesRequest.SerializeToString,
            v1_dot_common_dot_common__pb2.BatchOperationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessageStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.messaging.MessagingService/GetMessageStatus',
            v1_dot_messaging_dot_messaging__pb2.GetMessageStatusRequest.SerializeToString,
            v1_dot_messaging_dot_messaging__pb2.MessageStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.messaging.MessagingService/ListMessages',
            v1_dot_messaging_dot_messaging__pb2.ListMessagesRequest.SerializeToString,
            v1_dot_messaging_dot_messaging__pb2.ListMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessageTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.messaging.MessagingService/GetMessageTemplate',
            v1_dot_messaging_dot_messaging__pb2.GetMessageTemplateRequest.SerializeToString,
            v1_dot_messaging_dot_messaging__pb2.MessageTemplate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMessageTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.messaging.MessagingService/ListMessageTemplates',
            v1_dot_messaging_dot_messaging__pb2.ListMessageTemplatesRequest.SerializeToString,
            v1_dot_messaging_dot_messaging__pb2.ListMessageTemplatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.messaging.MessagingService/Health',
            v1_dot_common_dot_common__pb2.HealthRequest.SerializeToString,
            v1_dot_common_dot_common__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
