# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from openai_ussd_kernel.protos.v1.common import common_pb2 as v1_dot_common_dot_common__pb2
from openai_ussd_kernel.protos.v1.reconciliation import reconciliation_pb2 as v1_dot_reconciliation_dot_reconciliation__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in v1/reconciliation/reconciliation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReconciliationServiceStub(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - RECONCILIATION SERVICE (v1)
    =============================================================================
    Bounded Context: Reconciliation Engine
    Responsibility: Provider statement matching, discrepancy resolution,
    matching rule management, and regulatory reporting.
    Language: Go / Rust.
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartReconciliation = channel.unary_unary(
                '/ussd.v1.reconciliation.ReconciliationService/StartReconciliation',
                request_serializer=v1_dot_reconciliation_dot_reconciliation__pb2.StartReconciliationRequest.SerializeToString,
                response_deserializer=v1_dot_reconciliation_dot_reconciliation__pb2.ReconciliationRun.FromString,
                _registered_method=True)
        self.GetReconciliationRun = channel.unary_unary(
                '/ussd.v1.reconciliation.ReconciliationService/GetReconciliationRun',
                request_serializer=v1_dot_reconciliation_dot_reconciliation__pb2.GetReconciliationRunRequest.SerializeToString,
                response_deserializer=v1_dot_reconciliation_dot_reconciliation__pb2.ReconciliationRun.FromString,
                _registered_method=True)
        self.ListReconciliationRuns = channel.unary_unary(
                '/ussd.v1.reconciliation.ReconciliationService/ListReconciliationRuns',
                request_serializer=v1_dot_reconciliation_dot_reconciliation__pb2.ListReconciliationRunsRequest.SerializeToString,
                response_deserializer=v1_dot_reconciliation_dot_reconciliation__pb2.ListReconciliationRunsResponse.FromString,
                _registered_method=True)
        self.GetReconciliationItems = channel.unary_unary(
                '/ussd.v1.reconciliation.ReconciliationService/GetReconciliationItems',
                request_serializer=v1_dot_reconciliation_dot_reconciliation__pb2.GetReconciliationItemsRequest.SerializeToString,
                response_deserializer=v1_dot_reconciliation_dot_reconciliation__pb2.GetReconciliationItemsResponse.FromString,
                _registered_method=True)
        self.ResolveDiscrepancy = channel.unary_unary(
                '/ussd.v1.reconciliation.ReconciliationService/ResolveDiscrepancy',
                request_serializer=v1_dot_reconciliation_dot_reconciliation__pb2.ResolveDiscrepancyRequest.SerializeToString,
                response_deserializer=v1_dot_reconciliation_dot_reconciliation__pb2.ReconciliationItem.FromString,
                _registered_method=True)
        self.BulkResolveDiscrepancies = channel.unary_unary(
                '/ussd.v1.reconciliation.ReconciliationService/BulkResolveDiscrepancies',
                request_serializer=v1_dot_reconciliation_dot_reconciliation__pb2.BulkResolveDiscrepanciesRequest.SerializeToString,
                response_deserializer=v1_dot_common_dot_common__pb2.BatchOperationResult.FromString,
                _registered_method=True)
        self.GenerateReport = channel.unary_unary(
                '/ussd.v1.reconciliation.ReconciliationService/GenerateReport',
                request_serializer=v1_dot_reconciliation_dot_reconciliation__pb2.GenerateReportRequest.SerializeToString,
                response_deserializer=v1_dot_reconciliation_dot_reconciliation__pb2.GenerateReportResponse.FromString,
                _registered_method=True)
        self.GetMatchingRule = channel.unary_unary(
                '/ussd.v1.reconciliation.ReconciliationService/GetMatchingRule',
                request_serializer=v1_dot_reconciliation_dot_reconciliation__pb2.GetMatchingRuleRequest.SerializeToString,
                response_deserializer=v1_dot_reconciliation_dot_reconciliation__pb2.MatchingRule.FromString,
                _registered_method=True)
        self.ListMatchingRules = channel.unary_unary(
                '/ussd.v1.reconciliation.ReconciliationService/ListMatchingRules',
                request_serializer=v1_dot_reconciliation_dot_reconciliation__pb2.ListMatchingRulesRequest.SerializeToString,
                response_deserializer=v1_dot_reconciliation_dot_reconciliation__pb2.ListMatchingRulesResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ussd.v1.reconciliation.ReconciliationService/Health',
                request_serializer=v1_dot_common_dot_common__pb2.HealthRequest.SerializeToString,
                response_deserializer=v1_dot_common_dot_common__pb2.HealthResponse.FromString,
                _registered_method=True)


class ReconciliationServiceServicer(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - RECONCILIATION SERVICE (v1)
    =============================================================================
    Bounded Context: Reconciliation Engine
    Responsibility: Provider statement matching, discrepancy resolution,
    matching rule management, and regulatory reporting.
    Language: Go / Rust.
    =============================================================================

    """

    def StartReconciliation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReconciliationRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReconciliationRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReconciliationItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveDiscrepancy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkResolveDiscrepancies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMatchingRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMatchingRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReconciliationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartReconciliation': grpc.unary_unary_rpc_method_handler(
                    servicer.StartReconciliation,
                    request_deserializer=v1_dot_reconciliation_dot_reconciliation__pb2.StartReconciliationRequest.FromString,
                    response_serializer=v1_dot_reconciliation_dot_reconciliation__pb2.ReconciliationRun.SerializeToString,
            ),
            'GetReconciliationRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReconciliationRun,
                    request_deserializer=v1_dot_reconciliation_dot_reconciliation__pb2.GetReconciliationRunRequest.FromString,
                    response_serializer=v1_dot_reconciliation_dot_reconciliation__pb2.ReconciliationRun.SerializeToString,
            ),
            'ListReconciliationRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReconciliationRuns,
                    request_deserializer=v1_dot_reconciliation_dot_reconciliation__pb2.ListReconciliationRunsRequest.FromString,
                    response_serializer=v1_dot_reconciliation_dot_reconciliation__pb2.ListReconciliationRunsResponse.SerializeToString,
            ),
            'GetReconciliationItems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReconciliationItems,
                    request_deserializer=v1_dot_reconciliation_dot_reconciliation__pb2.GetReconciliationItemsRequest.FromString,
                    response_serializer=v1_dot_reconciliation_dot_reconciliation__pb2.GetReconciliationItemsResponse.SerializeToString,
            ),
            'ResolveDiscrepancy': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveDiscrepancy,
                    request_deserializer=v1_dot_reconciliation_dot_reconciliation__pb2.ResolveDiscrepancyRequest.FromString,
                    response_serializer=v1_dot_reconciliation_dot_reconciliation__pb2.ReconciliationItem.SerializeToString,
            ),
            'BulkResolveDiscrepancies': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkResolveDiscrepancies,
                    request_deserializer=v1_dot_reconciliation_dot_reconciliation__pb2.BulkResolveDiscrepanciesRequest.FromString,
                    response_serializer=v1_dot_common_dot_common__pb2.BatchOperationResult.SerializeToString,
            ),
            'GenerateReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReport,
                    request_deserializer=v1_dot_reconciliation_dot_reconciliation__pb2.GenerateReportRequest.FromString,
                    response_serializer=v1_dot_reconciliation_dot_reconciliation__pb2.GenerateReportResponse.SerializeToString,
            ),
            'GetMatchingRule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMatchingRule,
                    request_deserializer=v1_dot_reconciliation_dot_reconciliation__pb2.GetMatchingRuleRequest.FromString,
                    response_serializer=v1_dot_reconciliation_dot_reconciliation__pb2.MatchingRule.SerializeToString,
            ),
            'ListMatchingRules': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMatchingRules,
                    request_deserializer=v1_dot_reconciliation_dot_reconciliation__pb2.ListMatchingRulesRequest.FromString,
                    response_serializer=v1_dot_reconciliation_dot_reconciliation__pb2.ListMatchingRulesResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=v1_dot_common_dot_common__pb2.HealthRequest.FromString,
                    response_serializer=v1_dot_common_dot_common__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ussd.v1.reconciliation.ReconciliationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ussd.v1.reconciliation.ReconciliationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReconciliationService(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - RECONCILIATION SERVICE (v1)
    =============================================================================
    Bounded Context: Reconciliation Engine
    Responsibility: Provider statement matching, discrepancy resolution,
    matching rule management, and regulatory reporting.
    Language: Go / Rust.
    =============================================================================

    """

    @staticmethod
    def StartReconciliation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.reconciliation.ReconciliationService/StartReconciliation',
            v1_dot_reconciliation_dot_reconciliation__pb2.StartReconciliationRequest.SerializeToString,
            v1_dot_reconciliation_dot_reconciliation__pb2.ReconciliationRun.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReconciliationRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.reconciliation.ReconciliationService/GetReconciliationRun',
            v1_dot_reconciliation_dot_reconciliation__pb2.GetReconciliationRunRequest.SerializeToString,
            v1_dot_reconciliation_dot_reconciliation__pb2.ReconciliationRun.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReconciliationRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.reconciliation.ReconciliationService/ListReconciliationRuns',
            v1_dot_reconciliation_dot_reconciliation__pb2.ListReconciliationRunsRequest.SerializeToString,
            v1_dot_reconciliation_dot_reconciliation__pb2.ListReconciliationRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReconciliationItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.reconciliation.ReconciliationService/GetReconciliationItems',
            v1_dot_reconciliation_dot_reconciliation__pb2.GetReconciliationItemsRequest.SerializeToString,
            v1_dot_reconciliation_dot_reconciliation__pb2.GetReconciliationItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveDiscrepancy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.reconciliation.ReconciliationService/ResolveDiscrepancy',
            v1_dot_reconciliation_dot_reconciliation__pb2.ResolveDiscrepancyRequest.SerializeToString,
            v1_dot_reconciliation_dot_reconciliation__pb2.ReconciliationItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkResolveDiscrepancies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.reconciliation.ReconciliationService/BulkResolveDiscrepancies',
            v1_dot_reconciliation_dot_reconciliation__pb2.BulkResolveDiscrepanciesRequest.SerializeToString,
            v1_dot_common_dot_common__pb2.BatchOperationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.reconciliation.ReconciliationService/GenerateReport',
            v1_dot_reconciliation_dot_reconciliation__pb2.GenerateReportRequest.SerializeToString,
            v1_dot_reconciliation_dot_reconciliation__pb2.GenerateReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMatchingRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.reconciliation.ReconciliationService/GetMatchingRule',
            v1_dot_reconciliation_dot_reconciliation__pb2.GetMatchingRuleRequest.SerializeToString,
            v1_dot_reconciliation_dot_reconciliation__pb2.MatchingRule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMatchingRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.reconciliation.ReconciliationService/ListMatchingRules',
            v1_dot_reconciliation_dot_reconciliation__pb2.ListMatchingRulesRequest.SerializeToString,
            v1_dot_reconciliation_dot_reconciliation__pb2.ListMatchingRulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.reconciliation.ReconciliationService/Health',
            v1_dot_common_dot_common__pb2.HealthRequest.SerializeToString,
            v1_dot_common_dot_common__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
