# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from openai_ussd_kernel.protos.v1.common import common_pb2 as v1_dot_common_dot_common__pb2
from openai_ussd_kernel.protos.v1.gateway import gateway_pb2 as v1_dot_gateway_dot_gateway__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in v1/gateway/gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class USSDGatewayStub(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - USSD GATEWAY SERVICE (v1)
    =============================================================================
    Bounded Context: USSD Gateway
    Responsibility: Africa's Talking integration point. Receives USSD requests
    from external gateway, returns formatted responses, manages provider adapters,
    batch USSD campaigns, and webhook ingestion.
    Language: Python (Flask/FastAPI handler).
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveUSSD = channel.unary_unary(
                '/ussd.v1.gateway.USSDGateway/ReceiveUSSD',
                request_serializer=v1_dot_gateway_dot_gateway__pb2.USSDRequest.SerializeToString,
                response_deserializer=v1_dot_gateway_dot_gateway__pb2.USSDResponse.FromString,
                _registered_method=True)
        self.SendBatchUSSD = channel.unary_unary(
                '/ussd.v1.gateway.USSDGateway/SendBatchUSSD',
                request_serializer=v1_dot_gateway_dot_gateway__pb2.SendBatchUSSDRequest.SerializeToString,
                response_deserializer=v1_dot_common_dot_common__pb2.BatchOperationResult.FromString,
                _registered_method=True)
        self.GetBatchStatus = channel.unary_unary(
                '/ussd.v1.gateway.USSDGateway/GetBatchStatus',
                request_serializer=v1_dot_gateway_dot_gateway__pb2.GetBatchStatusRequest.SerializeToString,
                response_deserializer=v1_dot_gateway_dot_gateway__pb2.BatchStatusResponse.FromString,
                _registered_method=True)
        self.ProcessWebhook = channel.unary_unary(
                '/ussd.v1.gateway.USSDGateway/ProcessWebhook',
                request_serializer=v1_dot_gateway_dot_gateway__pb2.ProcessWebhookRequest.SerializeToString,
                response_deserializer=v1_dot_gateway_dot_gateway__pb2.ProcessWebhookResponse.FromString,
                _registered_method=True)
        self.ValidateWebhookSignature = channel.unary_unary(
                '/ussd.v1.gateway.USSDGateway/ValidateWebhookSignature',
                request_serializer=v1_dot_gateway_dot_gateway__pb2.ValidateWebhookSignatureRequest.SerializeToString,
                response_deserializer=v1_dot_gateway_dot_gateway__pb2.ValidateWebhookSignatureResponse.FromString,
                _registered_method=True)
        self.GetProviderAdapter = channel.unary_unary(
                '/ussd.v1.gateway.USSDGateway/GetProviderAdapter',
                request_serializer=v1_dot_gateway_dot_gateway__pb2.GetProviderAdapterRequest.SerializeToString,
                response_deserializer=v1_dot_gateway_dot_gateway__pb2.ProviderAdapter.FromString,
                _registered_method=True)
        self.ListProviderAdapters = channel.unary_unary(
                '/ussd.v1.gateway.USSDGateway/ListProviderAdapters',
                request_serializer=v1_dot_gateway_dot_gateway__pb2.ListProviderAdaptersRequest.SerializeToString,
                response_deserializer=v1_dot_gateway_dot_gateway__pb2.ListProviderAdaptersResponse.FromString,
                _registered_method=True)
        self.GetWebhookLog = channel.unary_unary(
                '/ussd.v1.gateway.USSDGateway/GetWebhookLog',
                request_serializer=v1_dot_gateway_dot_gateway__pb2.GetWebhookLogRequest.SerializeToString,
                response_deserializer=v1_dot_gateway_dot_gateway__pb2.WebhookLogEntry.FromString,
                _registered_method=True)
        self.ListWebhookLogs = channel.unary_unary(
                '/ussd.v1.gateway.USSDGateway/ListWebhookLogs',
                request_serializer=v1_dot_gateway_dot_gateway__pb2.ListWebhookLogsRequest.SerializeToString,
                response_deserializer=v1_dot_gateway_dot_gateway__pb2.ListWebhookLogsResponse.FromString,
                _registered_method=True)
        self.GetDeadLetterQueue = channel.unary_unary(
                '/ussd.v1.gateway.USSDGateway/GetDeadLetterQueue',
                request_serializer=v1_dot_gateway_dot_gateway__pb2.GetDeadLetterQueueRequest.SerializeToString,
                response_deserializer=v1_dot_gateway_dot_gateway__pb2.ListDeadLetterQueueResponse.FromString,
                _registered_method=True)
        self.ReplayDeadLetter = channel.unary_unary(
                '/ussd.v1.gateway.USSDGateway/ReplayDeadLetter',
                request_serializer=v1_dot_gateway_dot_gateway__pb2.ReplayDeadLetterRequest.SerializeToString,
                response_deserializer=v1_dot_gateway_dot_gateway__pb2.ReplayDeadLetterResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ussd.v1.gateway.USSDGateway/Health',
                request_serializer=v1_dot_common_dot_common__pb2.HealthRequest.SerializeToString,
                response_deserializer=v1_dot_common_dot_common__pb2.HealthResponse.FromString,
                _registered_method=True)


class USSDGatewayServicer(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - USSD GATEWAY SERVICE (v1)
    =============================================================================
    Bounded Context: USSD Gateway
    Responsibility: Africa's Talking integration point. Receives USSD requests
    from external gateway, returns formatted responses, manages provider adapters,
    batch USSD campaigns, and webhook ingestion.
    Language: Python (Flask/FastAPI handler).
    =============================================================================

    """

    def ReceiveUSSD(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendBatchUSSD(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBatchStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessWebhook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateWebhookSignature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProviderAdapter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProviderAdapters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWebhookLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWebhookLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeadLetterQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplayDeadLetter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_USSDGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveUSSD': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveUSSD,
                    request_deserializer=v1_dot_gateway_dot_gateway__pb2.USSDRequest.FromString,
                    response_serializer=v1_dot_gateway_dot_gateway__pb2.USSDResponse.SerializeToString,
            ),
            'SendBatchUSSD': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBatchUSSD,
                    request_deserializer=v1_dot_gateway_dot_gateway__pb2.SendBatchUSSDRequest.FromString,
                    response_serializer=v1_dot_common_dot_common__pb2.BatchOperationResult.SerializeToString,
            ),
            'GetBatchStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBatchStatus,
                    request_deserializer=v1_dot_gateway_dot_gateway__pb2.GetBatchStatusRequest.FromString,
                    response_serializer=v1_dot_gateway_dot_gateway__pb2.BatchStatusResponse.SerializeToString,
            ),
            'ProcessWebhook': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessWebhook,
                    request_deserializer=v1_dot_gateway_dot_gateway__pb2.ProcessWebhookRequest.FromString,
                    response_serializer=v1_dot_gateway_dot_gateway__pb2.ProcessWebhookResponse.SerializeToString,
            ),
            'ValidateWebhookSignature': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateWebhookSignature,
                    request_deserializer=v1_dot_gateway_dot_gateway__pb2.ValidateWebhookSignatureRequest.FromString,
                    response_serializer=v1_dot_gateway_dot_gateway__pb2.ValidateWebhookSignatureResponse.SerializeToString,
            ),
            'GetProviderAdapter': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProviderAdapter,
                    request_deserializer=v1_dot_gateway_dot_gateway__pb2.GetProviderAdapterRequest.FromString,
                    response_serializer=v1_dot_gateway_dot_gateway__pb2.ProviderAdapter.SerializeToString,
            ),
            'ListProviderAdapters': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProviderAdapters,
                    request_deserializer=v1_dot_gateway_dot_gateway__pb2.ListProviderAdaptersRequest.FromString,
                    response_serializer=v1_dot_gateway_dot_gateway__pb2.ListProviderAdaptersResponse.SerializeToString,
            ),
            'GetWebhookLog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWebhookLog,
                    request_deserializer=v1_dot_gateway_dot_gateway__pb2.GetWebhookLogRequest.FromString,
                    response_serializer=v1_dot_gateway_dot_gateway__pb2.WebhookLogEntry.SerializeToString,
            ),
            'ListWebhookLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWebhookLogs,
                    request_deserializer=v1_dot_gateway_dot_gateway__pb2.ListWebhookLogsRequest.FromString,
                    response_serializer=v1_dot_gateway_dot_gateway__pb2.ListWebhookLogsResponse.SerializeToString,
            ),
            'GetDeadLetterQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeadLetterQueue,
                    request_deserializer=v1_dot_gateway_dot_gateway__pb2.GetDeadLetterQueueRequest.FromString,
                    response_serializer=v1_dot_gateway_dot_gateway__pb2.ListDeadLetterQueueResponse.SerializeToString,
            ),
            'ReplayDeadLetter': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplayDeadLetter,
                    request_deserializer=v1_dot_gateway_dot_gateway__pb2.ReplayDeadLetterRequest.FromString,
                    response_serializer=v1_dot_gateway_dot_gateway__pb2.ReplayDeadLetterResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=v1_dot_common_dot_common__pb2.HealthRequest.FromString,
                    response_serializer=v1_dot_common_dot_common__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ussd.v1.gateway.USSDGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ussd.v1.gateway.USSDGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class USSDGateway(object):
    """=============================================================================
    OPEN AI-USSD KERNEL ENGINE - USSD GATEWAY SERVICE (v1)
    =============================================================================
    Bounded Context: USSD Gateway
    Responsibility: Africa's Talking integration point. Receives USSD requests
    from external gateway, returns formatted responses, manages provider adapters,
    batch USSD campaigns, and webhook ingestion.
    Language: Python (Flask/FastAPI handler).
    =============================================================================

    """

    @staticmethod
    def ReceiveUSSD(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.gateway.USSDGateway/ReceiveUSSD',
            v1_dot_gateway_dot_gateway__pb2.USSDRequest.SerializeToString,
            v1_dot_gateway_dot_gateway__pb2.USSDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendBatchUSSD(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.gateway.USSDGateway/SendBatchUSSD',
            v1_dot_gateway_dot_gateway__pb2.SendBatchUSSDRequest.SerializeToString,
            v1_dot_common_dot_common__pb2.BatchOperationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBatchStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.gateway.USSDGateway/GetBatchStatus',
            v1_dot_gateway_dot_gateway__pb2.GetBatchStatusRequest.SerializeToString,
            v1_dot_gateway_dot_gateway__pb2.BatchStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessWebhook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.gateway.USSDGateway/ProcessWebhook',
            v1_dot_gateway_dot_gateway__pb2.ProcessWebhookRequest.SerializeToString,
            v1_dot_gateway_dot_gateway__pb2.ProcessWebhookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateWebhookSignature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.gateway.USSDGateway/ValidateWebhookSignature',
            v1_dot_gateway_dot_gateway__pb2.ValidateWebhookSignatureRequest.SerializeToString,
            v1_dot_gateway_dot_gateway__pb2.ValidateWebhookSignatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProviderAdapter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.gateway.USSDGateway/GetProviderAdapter',
            v1_dot_gateway_dot_gateway__pb2.GetProviderAdapterRequest.SerializeToString,
            v1_dot_gateway_dot_gateway__pb2.ProviderAdapter.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProviderAdapters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.gateway.USSDGateway/ListProviderAdapters',
            v1_dot_gateway_dot_gateway__pb2.ListProviderAdaptersRequest.SerializeToString,
            v1_dot_gateway_dot_gateway__pb2.ListProviderAdaptersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWebhookLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.gateway.USSDGateway/GetWebhookLog',
            v1_dot_gateway_dot_gateway__pb2.GetWebhookLogRequest.SerializeToString,
            v1_dot_gateway_dot_gateway__pb2.WebhookLogEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWebhookLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.gateway.USSDGateway/ListWebhookLogs',
            v1_dot_gateway_dot_gateway__pb2.ListWebhookLogsRequest.SerializeToString,
            v1_dot_gateway_dot_gateway__pb2.ListWebhookLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeadLetterQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.gateway.USSDGateway/GetDeadLetterQueue',
            v1_dot_gateway_dot_gateway__pb2.GetDeadLetterQueueRequest.SerializeToString,
            v1_dot_gateway_dot_gateway__pb2.ListDeadLetterQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplayDeadLetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.gateway.USSDGateway/ReplayDeadLetter',
            v1_dot_gateway_dot_gateway__pb2.ReplayDeadLetterRequest.SerializeToString,
            v1_dot_gateway_dot_gateway__pb2.ReplayDeadLetterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ussd.v1.gateway.USSDGateway/Health',
            v1_dot_common_dot_common__pb2.HealthRequest.SerializeToString,
            v1_dot_common_dot_common__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
