apiVersion: v1
kind: Service
metadata:
  name: go-orchestrator
  namespace: open-ai-ussd-kernel
  labels:
    app.kubernetes.io/name: go-orchestrator
    app.kubernetes.io/component: orchestrator
spec:
  selector:
    app.kubernetes.io/name: go-orchestrator
  ports:
    - port: 9090
      targetPort: 9090
      name: grpc
    - port: 9091
      targetPort: 9091
      name: admin-grpc
    - port: 8080
      targetPort: 8080
      name: metrics
  type: ClusterIP
