apiVersion: v1
kind: Secret
metadata:
  name: payment-engine-secret
  namespace: open-ai-ussd-kernel
  labels:
    app.kubernetes.io/name: payment-engine
    app.kubernetes.io/component: secret
type: Opaque
data:
  # Base64 placeholders
  ECOCASH_BASE_URL: ""
  ECOCASH_MERCHANT_ID: ""
  ECOCASH_API_KEY: ""
  ECOCASH_SECRET_KEY: ""
